// Code generated by ent, DO NOT EDIT.

package trustedca

import (
	"PostmanJanai/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldLTE(FieldID, id))
}

// PemContent applies equality check predicate on the "pem_content" field. It's identical to PemContentEQ.
func PemContent(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldEQ(FieldPemContent, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldEQ(FieldCreatedAt, v))
}

// LabelEQ applies the EQ predicate on the "label" field.
func LabelEQ(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldEQ(FieldLabel, v))
}

// LabelNEQ applies the NEQ predicate on the "label" field.
func LabelNEQ(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldNEQ(FieldLabel, v))
}

// LabelIn applies the In predicate on the "label" field.
func LabelIn(vs ...string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldIn(FieldLabel, vs...))
}

// LabelNotIn applies the NotIn predicate on the "label" field.
func LabelNotIn(vs ...string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldNotIn(FieldLabel, vs...))
}

// LabelGT applies the GT predicate on the "label" field.
func LabelGT(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldGT(FieldLabel, v))
}

// LabelGTE applies the GTE predicate on the "label" field.
func LabelGTE(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldGTE(FieldLabel, v))
}

// LabelLT applies the LT predicate on the "label" field.
func LabelLT(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldLT(FieldLabel, v))
}

// LabelLTE applies the LTE predicate on the "label" field.
func LabelLTE(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldLTE(FieldLabel, v))
}

// LabelContains applies the Contains predicate on the "label" field.
func LabelContains(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldContains(FieldLabel, v))
}

// LabelHasPrefix applies the HasPrefix predicate on the "label" field.
func LabelHasPrefix(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldHasPrefix(FieldLabel, v))
}

// LabelHasSuffix applies the HasSuffix predicate on the "label" field.
func LabelHasSuffix(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldHasSuffix(FieldLabel, v))
}

// LabelEqualFold applies the EqualFold predicate on the "label" field.
func LabelEqualFold(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldEqualFold(FieldLabel, v))
}

// LabelContainsFold applies the ContainsFold predicate on the "label" field.
func LabelContainsFold(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldContainsFold(FieldLabel, v))
}

// PemContentEQ applies the EQ predicate on the "pem_content" field.
func PemContentEQ(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldEQ(FieldPemContent, v))
}

// PemContentNEQ applies the NEQ predicate on the "pem_content" field.
func PemContentNEQ(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldNEQ(FieldPemContent, v))
}

// PemContentIn applies the In predicate on the "pem_content" field.
func PemContentIn(vs ...string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldIn(FieldPemContent, vs...))
}

// PemContentNotIn applies the NotIn predicate on the "pem_content" field.
func PemContentNotIn(vs ...string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldNotIn(FieldPemContent, vs...))
}

// PemContentGT applies the GT predicate on the "pem_content" field.
func PemContentGT(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldGT(FieldPemContent, v))
}

// PemContentGTE applies the GTE predicate on the "pem_content" field.
func PemContentGTE(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldGTE(FieldPemContent, v))
}

// PemContentLT applies the LT predicate on the "pem_content" field.
func PemContentLT(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldLT(FieldPemContent, v))
}

// PemContentLTE applies the LTE predicate on the "pem_content" field.
func PemContentLTE(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldLTE(FieldPemContent, v))
}

// PemContentContains applies the Contains predicate on the "pem_content" field.
func PemContentContains(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldContains(FieldPemContent, v))
}

// PemContentHasPrefix applies the HasPrefix predicate on the "pem_content" field.
func PemContentHasPrefix(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldHasPrefix(FieldPemContent, v))
}

// PemContentHasSuffix applies the HasSuffix predicate on the "pem_content" field.
func PemContentHasSuffix(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldHasSuffix(FieldPemContent, v))
}

// PemContentEqualFold applies the EqualFold predicate on the "pem_content" field.
func PemContentEqualFold(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldEqualFold(FieldPemContent, v))
}

// PemContentContainsFold applies the ContainsFold predicate on the "pem_content" field.
func PemContentContainsFold(v string) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldContainsFold(FieldPemContent, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldNEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TrustedCA {
	return predicate.TrustedCA(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TrustedCA) predicate.TrustedCA {
	return predicate.TrustedCA(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TrustedCA) predicate.TrustedCA {
	return predicate.TrustedCA(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TrustedCA) predicate.TrustedCA {
	return predicate.TrustedCA(sql.NotPredicates(p))
}
