// Code generated by ent, DO NOT EDIT.

package requestformfield

import (
	"PostmanJanai/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldLTE(FieldID, id))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldRequestID, v))
}

// FieldKind applies equality check predicate on the "field_kind" field. It's identical to FieldKindEQ.
func FieldKind(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldFieldKind, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldKey, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldValue, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldEnabled, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldSortOrder, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...uuid.UUID) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNotIn(FieldRequestID, vs...))
}

// FieldKindEQ applies the EQ predicate on the "field_kind" field.
func FieldKindEQ(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldFieldKind, v))
}

// FieldKindNEQ applies the NEQ predicate on the "field_kind" field.
func FieldKindNEQ(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNEQ(FieldFieldKind, v))
}

// FieldKindIn applies the In predicate on the "field_kind" field.
func FieldKindIn(vs ...string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldIn(FieldFieldKind, vs...))
}

// FieldKindNotIn applies the NotIn predicate on the "field_kind" field.
func FieldKindNotIn(vs ...string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNotIn(FieldFieldKind, vs...))
}

// FieldKindGT applies the GT predicate on the "field_kind" field.
func FieldKindGT(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldGT(FieldFieldKind, v))
}

// FieldKindGTE applies the GTE predicate on the "field_kind" field.
func FieldKindGTE(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldGTE(FieldFieldKind, v))
}

// FieldKindLT applies the LT predicate on the "field_kind" field.
func FieldKindLT(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldLT(FieldFieldKind, v))
}

// FieldKindLTE applies the LTE predicate on the "field_kind" field.
func FieldKindLTE(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldLTE(FieldFieldKind, v))
}

// FieldKindContains applies the Contains predicate on the "field_kind" field.
func FieldKindContains(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldContains(FieldFieldKind, v))
}

// FieldKindHasPrefix applies the HasPrefix predicate on the "field_kind" field.
func FieldKindHasPrefix(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldHasPrefix(FieldFieldKind, v))
}

// FieldKindHasSuffix applies the HasSuffix predicate on the "field_kind" field.
func FieldKindHasSuffix(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldHasSuffix(FieldFieldKind, v))
}

// FieldKindEqualFold applies the EqualFold predicate on the "field_kind" field.
func FieldKindEqualFold(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEqualFold(FieldFieldKind, v))
}

// FieldKindContainsFold applies the ContainsFold predicate on the "field_kind" field.
func FieldKindContainsFold(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldContainsFold(FieldFieldKind, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldContainsFold(FieldKey, v))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldLTE(FieldValue, v))
}

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldContains(FieldValue, v))
}

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldHasPrefix(FieldValue, v))
}

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldHasSuffix(FieldValue, v))
}

// ValueIsNil applies the IsNil predicate on the "value" field.
func ValueIsNil() predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldIsNull(FieldValue))
}

// ValueNotNil applies the NotNil predicate on the "value" field.
func ValueNotNil() predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNotNull(FieldValue))
}

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEqualFold(FieldValue, v))
}

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldContainsFold(FieldValue, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNEQ(FieldEnabled, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.RequestFormField {
	return predicate.RequestFormField(sql.FieldLTE(FieldSortOrder, v))
}

// HasRequest applies the HasEdge predicate on the "request" edge.
func HasRequest() predicate.RequestFormField {
	return predicate.RequestFormField(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RequestTable, RequestColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequestWith applies the HasEdge predicate on the "request" edge with a given conditions (other predicates).
func HasRequestWith(preds ...predicate.Request) predicate.RequestFormField {
	return predicate.RequestFormField(func(s *sql.Selector) {
		step := newRequestStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RequestFormField) predicate.RequestFormField {
	return predicate.RequestFormField(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RequestFormField) predicate.RequestFormField {
	return predicate.RequestFormField(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RequestFormField) predicate.RequestFormField {
	return predicate.RequestFormField(sql.NotPredicates(p))
}
