// Code generated by ent, DO NOT EDIT.

package history

import (
	"PostmanJanai/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.History {
	return predicate.History(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.History {
	return predicate.History(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.History {
	return predicate.History(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.History {
	return predicate.History(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.History {
	return predicate.History(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.History {
	return predicate.History(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.History {
	return predicate.History(sql.FieldLTE(FieldID, id))
}

// RootFolderID applies equality check predicate on the "root_folder_id" field. It's identical to RootFolderIDEQ.
func RootFolderID(v uuid.UUID) predicate.History {
	return predicate.History(sql.FieldEQ(FieldRootFolderID, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v uuid.UUID) predicate.History {
	return predicate.History(sql.FieldEQ(FieldRequestID, v))
}

// Method applies equality check predicate on the "method" field. It's identical to MethodEQ.
func Method(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldMethod, v))
}

// URL applies equality check predicate on the "url" field. It's identical to URLEQ.
func URL(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldURL, v))
}

// StatusCode applies equality check predicate on the "status_code" field. It's identical to StatusCodeEQ.
func StatusCode(v int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldStatusCode, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldDurationMs, v))
}

// ResponseSizeBytes applies equality check predicate on the "response_size_bytes" field. It's identical to ResponseSizeBytesEQ.
func ResponseSizeBytes(v int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldResponseSizeBytes, v))
}

// RequestHeadersJSON applies equality check predicate on the "request_headers_json" field. It's identical to RequestHeadersJSONEQ.
func RequestHeadersJSON(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldRequestHeadersJSON, v))
}

// ResponseHeadersJSON applies equality check predicate on the "response_headers_json" field. It's identical to ResponseHeadersJSONEQ.
func ResponseHeadersJSON(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldResponseHeadersJSON, v))
}

// RequestBody applies equality check predicate on the "request_body" field. It's identical to RequestBodyEQ.
func RequestBody(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldRequestBody, v))
}

// ResponseBody applies equality check predicate on the "response_body" field. It's identical to ResponseBodyEQ.
func ResponseBody(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldResponseBody, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.History {
	return predicate.History(sql.FieldEQ(FieldCreatedAt, v))
}

// RootFolderIDEQ applies the EQ predicate on the "root_folder_id" field.
func RootFolderIDEQ(v uuid.UUID) predicate.History {
	return predicate.History(sql.FieldEQ(FieldRootFolderID, v))
}

// RootFolderIDNEQ applies the NEQ predicate on the "root_folder_id" field.
func RootFolderIDNEQ(v uuid.UUID) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldRootFolderID, v))
}

// RootFolderIDIn applies the In predicate on the "root_folder_id" field.
func RootFolderIDIn(vs ...uuid.UUID) predicate.History {
	return predicate.History(sql.FieldIn(FieldRootFolderID, vs...))
}

// RootFolderIDNotIn applies the NotIn predicate on the "root_folder_id" field.
func RootFolderIDNotIn(vs ...uuid.UUID) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldRootFolderID, vs...))
}

// RootFolderIDIsNil applies the IsNil predicate on the "root_folder_id" field.
func RootFolderIDIsNil() predicate.History {
	return predicate.History(sql.FieldIsNull(FieldRootFolderID))
}

// RootFolderIDNotNil applies the NotNil predicate on the "root_folder_id" field.
func RootFolderIDNotNil() predicate.History {
	return predicate.History(sql.FieldNotNull(FieldRootFolderID))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v uuid.UUID) predicate.History {
	return predicate.History(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v uuid.UUID) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...uuid.UUID) predicate.History {
	return predicate.History(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...uuid.UUID) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.History {
	return predicate.History(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.History {
	return predicate.History(sql.FieldNotNull(FieldRequestID))
}

// MethodEQ applies the EQ predicate on the "method" field.
func MethodEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldMethod, v))
}

// MethodNEQ applies the NEQ predicate on the "method" field.
func MethodNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldMethod, v))
}

// MethodIn applies the In predicate on the "method" field.
func MethodIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldMethod, vs...))
}

// MethodNotIn applies the NotIn predicate on the "method" field.
func MethodNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldMethod, vs...))
}

// MethodGT applies the GT predicate on the "method" field.
func MethodGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldMethod, v))
}

// MethodGTE applies the GTE predicate on the "method" field.
func MethodGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldMethod, v))
}

// MethodLT applies the LT predicate on the "method" field.
func MethodLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldMethod, v))
}

// MethodLTE applies the LTE predicate on the "method" field.
func MethodLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldMethod, v))
}

// MethodContains applies the Contains predicate on the "method" field.
func MethodContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldMethod, v))
}

// MethodHasPrefix applies the HasPrefix predicate on the "method" field.
func MethodHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldMethod, v))
}

// MethodHasSuffix applies the HasSuffix predicate on the "method" field.
func MethodHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldMethod, v))
}

// MethodEqualFold applies the EqualFold predicate on the "method" field.
func MethodEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldMethod, v))
}

// MethodContainsFold applies the ContainsFold predicate on the "method" field.
func MethodContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldMethod, v))
}

// URLEQ applies the EQ predicate on the "url" field.
func URLEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldURL, v))
}

// URLNEQ applies the NEQ predicate on the "url" field.
func URLNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldURL, v))
}

// URLIn applies the In predicate on the "url" field.
func URLIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldURL, vs...))
}

// URLNotIn applies the NotIn predicate on the "url" field.
func URLNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldURL, vs...))
}

// URLGT applies the GT predicate on the "url" field.
func URLGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldURL, v))
}

// URLGTE applies the GTE predicate on the "url" field.
func URLGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldURL, v))
}

// URLLT applies the LT predicate on the "url" field.
func URLLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldURL, v))
}

// URLLTE applies the LTE predicate on the "url" field.
func URLLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldURL, v))
}

// URLContains applies the Contains predicate on the "url" field.
func URLContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldURL, v))
}

// URLHasPrefix applies the HasPrefix predicate on the "url" field.
func URLHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldURL, v))
}

// URLHasSuffix applies the HasSuffix predicate on the "url" field.
func URLHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldURL, v))
}

// URLEqualFold applies the EqualFold predicate on the "url" field.
func URLEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldURL, v))
}

// URLContainsFold applies the ContainsFold predicate on the "url" field.
func URLContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldURL, v))
}

// StatusCodeEQ applies the EQ predicate on the "status_code" field.
func StatusCodeEQ(v int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldStatusCode, v))
}

// StatusCodeNEQ applies the NEQ predicate on the "status_code" field.
func StatusCodeNEQ(v int) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldStatusCode, v))
}

// StatusCodeIn applies the In predicate on the "status_code" field.
func StatusCodeIn(vs ...int) predicate.History {
	return predicate.History(sql.FieldIn(FieldStatusCode, vs...))
}

// StatusCodeNotIn applies the NotIn predicate on the "status_code" field.
func StatusCodeNotIn(vs ...int) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldStatusCode, vs...))
}

// StatusCodeGT applies the GT predicate on the "status_code" field.
func StatusCodeGT(v int) predicate.History {
	return predicate.History(sql.FieldGT(FieldStatusCode, v))
}

// StatusCodeGTE applies the GTE predicate on the "status_code" field.
func StatusCodeGTE(v int) predicate.History {
	return predicate.History(sql.FieldGTE(FieldStatusCode, v))
}

// StatusCodeLT applies the LT predicate on the "status_code" field.
func StatusCodeLT(v int) predicate.History {
	return predicate.History(sql.FieldLT(FieldStatusCode, v))
}

// StatusCodeLTE applies the LTE predicate on the "status_code" field.
func StatusCodeLTE(v int) predicate.History {
	return predicate.History(sql.FieldLTE(FieldStatusCode, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int) predicate.History {
	return predicate.History(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int) predicate.History {
	return predicate.History(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int) predicate.History {
	return predicate.History(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int) predicate.History {
	return predicate.History(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int) predicate.History {
	return predicate.History(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.History {
	return predicate.History(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.History {
	return predicate.History(sql.FieldNotNull(FieldDurationMs))
}

// ResponseSizeBytesEQ applies the EQ predicate on the "response_size_bytes" field.
func ResponseSizeBytesEQ(v int) predicate.History {
	return predicate.History(sql.FieldEQ(FieldResponseSizeBytes, v))
}

// ResponseSizeBytesNEQ applies the NEQ predicate on the "response_size_bytes" field.
func ResponseSizeBytesNEQ(v int) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldResponseSizeBytes, v))
}

// ResponseSizeBytesIn applies the In predicate on the "response_size_bytes" field.
func ResponseSizeBytesIn(vs ...int) predicate.History {
	return predicate.History(sql.FieldIn(FieldResponseSizeBytes, vs...))
}

// ResponseSizeBytesNotIn applies the NotIn predicate on the "response_size_bytes" field.
func ResponseSizeBytesNotIn(vs ...int) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldResponseSizeBytes, vs...))
}

// ResponseSizeBytesGT applies the GT predicate on the "response_size_bytes" field.
func ResponseSizeBytesGT(v int) predicate.History {
	return predicate.History(sql.FieldGT(FieldResponseSizeBytes, v))
}

// ResponseSizeBytesGTE applies the GTE predicate on the "response_size_bytes" field.
func ResponseSizeBytesGTE(v int) predicate.History {
	return predicate.History(sql.FieldGTE(FieldResponseSizeBytes, v))
}

// ResponseSizeBytesLT applies the LT predicate on the "response_size_bytes" field.
func ResponseSizeBytesLT(v int) predicate.History {
	return predicate.History(sql.FieldLT(FieldResponseSizeBytes, v))
}

// ResponseSizeBytesLTE applies the LTE predicate on the "response_size_bytes" field.
func ResponseSizeBytesLTE(v int) predicate.History {
	return predicate.History(sql.FieldLTE(FieldResponseSizeBytes, v))
}

// ResponseSizeBytesIsNil applies the IsNil predicate on the "response_size_bytes" field.
func ResponseSizeBytesIsNil() predicate.History {
	return predicate.History(sql.FieldIsNull(FieldResponseSizeBytes))
}

// ResponseSizeBytesNotNil applies the NotNil predicate on the "response_size_bytes" field.
func ResponseSizeBytesNotNil() predicate.History {
	return predicate.History(sql.FieldNotNull(FieldResponseSizeBytes))
}

// RequestHeadersJSONEQ applies the EQ predicate on the "request_headers_json" field.
func RequestHeadersJSONEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldRequestHeadersJSON, v))
}

// RequestHeadersJSONNEQ applies the NEQ predicate on the "request_headers_json" field.
func RequestHeadersJSONNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldRequestHeadersJSON, v))
}

// RequestHeadersJSONIn applies the In predicate on the "request_headers_json" field.
func RequestHeadersJSONIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldRequestHeadersJSON, vs...))
}

// RequestHeadersJSONNotIn applies the NotIn predicate on the "request_headers_json" field.
func RequestHeadersJSONNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldRequestHeadersJSON, vs...))
}

// RequestHeadersJSONGT applies the GT predicate on the "request_headers_json" field.
func RequestHeadersJSONGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldRequestHeadersJSON, v))
}

// RequestHeadersJSONGTE applies the GTE predicate on the "request_headers_json" field.
func RequestHeadersJSONGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldRequestHeadersJSON, v))
}

// RequestHeadersJSONLT applies the LT predicate on the "request_headers_json" field.
func RequestHeadersJSONLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldRequestHeadersJSON, v))
}

// RequestHeadersJSONLTE applies the LTE predicate on the "request_headers_json" field.
func RequestHeadersJSONLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldRequestHeadersJSON, v))
}

// RequestHeadersJSONContains applies the Contains predicate on the "request_headers_json" field.
func RequestHeadersJSONContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldRequestHeadersJSON, v))
}

// RequestHeadersJSONHasPrefix applies the HasPrefix predicate on the "request_headers_json" field.
func RequestHeadersJSONHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldRequestHeadersJSON, v))
}

// RequestHeadersJSONHasSuffix applies the HasSuffix predicate on the "request_headers_json" field.
func RequestHeadersJSONHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldRequestHeadersJSON, v))
}

// RequestHeadersJSONIsNil applies the IsNil predicate on the "request_headers_json" field.
func RequestHeadersJSONIsNil() predicate.History {
	return predicate.History(sql.FieldIsNull(FieldRequestHeadersJSON))
}

// RequestHeadersJSONNotNil applies the NotNil predicate on the "request_headers_json" field.
func RequestHeadersJSONNotNil() predicate.History {
	return predicate.History(sql.FieldNotNull(FieldRequestHeadersJSON))
}

// RequestHeadersJSONEqualFold applies the EqualFold predicate on the "request_headers_json" field.
func RequestHeadersJSONEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldRequestHeadersJSON, v))
}

// RequestHeadersJSONContainsFold applies the ContainsFold predicate on the "request_headers_json" field.
func RequestHeadersJSONContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldRequestHeadersJSON, v))
}

// ResponseHeadersJSONEQ applies the EQ predicate on the "response_headers_json" field.
func ResponseHeadersJSONEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldResponseHeadersJSON, v))
}

// ResponseHeadersJSONNEQ applies the NEQ predicate on the "response_headers_json" field.
func ResponseHeadersJSONNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldResponseHeadersJSON, v))
}

// ResponseHeadersJSONIn applies the In predicate on the "response_headers_json" field.
func ResponseHeadersJSONIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldResponseHeadersJSON, vs...))
}

// ResponseHeadersJSONNotIn applies the NotIn predicate on the "response_headers_json" field.
func ResponseHeadersJSONNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldResponseHeadersJSON, vs...))
}

// ResponseHeadersJSONGT applies the GT predicate on the "response_headers_json" field.
func ResponseHeadersJSONGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldResponseHeadersJSON, v))
}

// ResponseHeadersJSONGTE applies the GTE predicate on the "response_headers_json" field.
func ResponseHeadersJSONGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldResponseHeadersJSON, v))
}

// ResponseHeadersJSONLT applies the LT predicate on the "response_headers_json" field.
func ResponseHeadersJSONLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldResponseHeadersJSON, v))
}

// ResponseHeadersJSONLTE applies the LTE predicate on the "response_headers_json" field.
func ResponseHeadersJSONLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldResponseHeadersJSON, v))
}

// ResponseHeadersJSONContains applies the Contains predicate on the "response_headers_json" field.
func ResponseHeadersJSONContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldResponseHeadersJSON, v))
}

// ResponseHeadersJSONHasPrefix applies the HasPrefix predicate on the "response_headers_json" field.
func ResponseHeadersJSONHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldResponseHeadersJSON, v))
}

// ResponseHeadersJSONHasSuffix applies the HasSuffix predicate on the "response_headers_json" field.
func ResponseHeadersJSONHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldResponseHeadersJSON, v))
}

// ResponseHeadersJSONIsNil applies the IsNil predicate on the "response_headers_json" field.
func ResponseHeadersJSONIsNil() predicate.History {
	return predicate.History(sql.FieldIsNull(FieldResponseHeadersJSON))
}

// ResponseHeadersJSONNotNil applies the NotNil predicate on the "response_headers_json" field.
func ResponseHeadersJSONNotNil() predicate.History {
	return predicate.History(sql.FieldNotNull(FieldResponseHeadersJSON))
}

// ResponseHeadersJSONEqualFold applies the EqualFold predicate on the "response_headers_json" field.
func ResponseHeadersJSONEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldResponseHeadersJSON, v))
}

// ResponseHeadersJSONContainsFold applies the ContainsFold predicate on the "response_headers_json" field.
func ResponseHeadersJSONContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldResponseHeadersJSON, v))
}

// RequestBodyEQ applies the EQ predicate on the "request_body" field.
func RequestBodyEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldRequestBody, v))
}

// RequestBodyNEQ applies the NEQ predicate on the "request_body" field.
func RequestBodyNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldRequestBody, v))
}

// RequestBodyIn applies the In predicate on the "request_body" field.
func RequestBodyIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldRequestBody, vs...))
}

// RequestBodyNotIn applies the NotIn predicate on the "request_body" field.
func RequestBodyNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldRequestBody, vs...))
}

// RequestBodyGT applies the GT predicate on the "request_body" field.
func RequestBodyGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldRequestBody, v))
}

// RequestBodyGTE applies the GTE predicate on the "request_body" field.
func RequestBodyGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldRequestBody, v))
}

// RequestBodyLT applies the LT predicate on the "request_body" field.
func RequestBodyLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldRequestBody, v))
}

// RequestBodyLTE applies the LTE predicate on the "request_body" field.
func RequestBodyLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldRequestBody, v))
}

// RequestBodyContains applies the Contains predicate on the "request_body" field.
func RequestBodyContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldRequestBody, v))
}

// RequestBodyHasPrefix applies the HasPrefix predicate on the "request_body" field.
func RequestBodyHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldRequestBody, v))
}

// RequestBodyHasSuffix applies the HasSuffix predicate on the "request_body" field.
func RequestBodyHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldRequestBody, v))
}

// RequestBodyIsNil applies the IsNil predicate on the "request_body" field.
func RequestBodyIsNil() predicate.History {
	return predicate.History(sql.FieldIsNull(FieldRequestBody))
}

// RequestBodyNotNil applies the NotNil predicate on the "request_body" field.
func RequestBodyNotNil() predicate.History {
	return predicate.History(sql.FieldNotNull(FieldRequestBody))
}

// RequestBodyEqualFold applies the EqualFold predicate on the "request_body" field.
func RequestBodyEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldRequestBody, v))
}

// RequestBodyContainsFold applies the ContainsFold predicate on the "request_body" field.
func RequestBodyContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldRequestBody, v))
}

// ResponseBodyEQ applies the EQ predicate on the "response_body" field.
func ResponseBodyEQ(v string) predicate.History {
	return predicate.History(sql.FieldEQ(FieldResponseBody, v))
}

// ResponseBodyNEQ applies the NEQ predicate on the "response_body" field.
func ResponseBodyNEQ(v string) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldResponseBody, v))
}

// ResponseBodyIn applies the In predicate on the "response_body" field.
func ResponseBodyIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldIn(FieldResponseBody, vs...))
}

// ResponseBodyNotIn applies the NotIn predicate on the "response_body" field.
func ResponseBodyNotIn(vs ...string) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldResponseBody, vs...))
}

// ResponseBodyGT applies the GT predicate on the "response_body" field.
func ResponseBodyGT(v string) predicate.History {
	return predicate.History(sql.FieldGT(FieldResponseBody, v))
}

// ResponseBodyGTE applies the GTE predicate on the "response_body" field.
func ResponseBodyGTE(v string) predicate.History {
	return predicate.History(sql.FieldGTE(FieldResponseBody, v))
}

// ResponseBodyLT applies the LT predicate on the "response_body" field.
func ResponseBodyLT(v string) predicate.History {
	return predicate.History(sql.FieldLT(FieldResponseBody, v))
}

// ResponseBodyLTE applies the LTE predicate on the "response_body" field.
func ResponseBodyLTE(v string) predicate.History {
	return predicate.History(sql.FieldLTE(FieldResponseBody, v))
}

// ResponseBodyContains applies the Contains predicate on the "response_body" field.
func ResponseBodyContains(v string) predicate.History {
	return predicate.History(sql.FieldContains(FieldResponseBody, v))
}

// ResponseBodyHasPrefix applies the HasPrefix predicate on the "response_body" field.
func ResponseBodyHasPrefix(v string) predicate.History {
	return predicate.History(sql.FieldHasPrefix(FieldResponseBody, v))
}

// ResponseBodyHasSuffix applies the HasSuffix predicate on the "response_body" field.
func ResponseBodyHasSuffix(v string) predicate.History {
	return predicate.History(sql.FieldHasSuffix(FieldResponseBody, v))
}

// ResponseBodyIsNil applies the IsNil predicate on the "response_body" field.
func ResponseBodyIsNil() predicate.History {
	return predicate.History(sql.FieldIsNull(FieldResponseBody))
}

// ResponseBodyNotNil applies the NotNil predicate on the "response_body" field.
func ResponseBodyNotNil() predicate.History {
	return predicate.History(sql.FieldNotNull(FieldResponseBody))
}

// ResponseBodyEqualFold applies the EqualFold predicate on the "response_body" field.
func ResponseBodyEqualFold(v string) predicate.History {
	return predicate.History(sql.FieldEqualFold(FieldResponseBody, v))
}

// ResponseBodyContainsFold applies the ContainsFold predicate on the "response_body" field.
func ResponseBodyContainsFold(v string) predicate.History {
	return predicate.History(sql.FieldContainsFold(FieldResponseBody, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.History {
	return predicate.History(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.History {
	return predicate.History(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.History {
	return predicate.History(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.History {
	return predicate.History(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.History {
	return predicate.History(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.History {
	return predicate.History(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.History {
	return predicate.History(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.History {
	return predicate.History(sql.FieldLTE(FieldCreatedAt, v))
}

// HasRootFolder applies the HasEdge predicate on the "root_folder" edge.
func HasRootFolder() predicate.History {
	return predicate.History(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RootFolderTable, RootFolderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRootFolderWith applies the HasEdge predicate on the "root_folder" edge with a given conditions (other predicates).
func HasRootFolderWith(preds ...predicate.Folder) predicate.History {
	return predicate.History(func(s *sql.Selector) {
		step := newRootFolderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRequest applies the HasEdge predicate on the "request" edge.
func HasRequest() predicate.History {
	return predicate.History(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, RequestTable, RequestColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRequestWith applies the HasEdge predicate on the "request" edge with a given conditions (other predicates).
func HasRequestWith(preds ...predicate.Request) predicate.History {
	return predicate.History(func(s *sql.Selector) {
		step := newRequestStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.History) predicate.History {
	return predicate.History(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.History) predicate.History {
	return predicate.History(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.History) predicate.History {
	return predicate.History(sql.NotPredicates(p))
}
