// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EnvironmentsColumns holds the columns for the "environments" table.
	EnvironmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "is_active", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// EnvironmentsTable holds the schema information for the "environments" table.
	EnvironmentsTable = &schema.Table{
		Name:       "environments",
		Columns:    EnvironmentsColumns,
		PrimaryKey: []*schema.Column{EnvironmentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "environment_name",
				Unique:  true,
				Columns: []*schema.Column{EnvironmentsColumns[1]},
			},
		},
	}
	// EnvironmentVariablesColumns holds the columns for the "environment_variables" table.
	EnvironmentVariablesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "kind", Type: field.TypeString, Default: "plain"},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "environment_id", Type: field.TypeUUID},
	}
	// EnvironmentVariablesTable holds the schema information for the "environment_variables" table.
	EnvironmentVariablesTable = &schema.Table{
		Name:       "environment_variables",
		Columns:    EnvironmentVariablesColumns,
		PrimaryKey: []*schema.Column{EnvironmentVariablesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "environment_variables_environments_environment_variables",
				Columns:    []*schema.Column{EnvironmentVariablesColumns[8]},
				RefColumns: []*schema.Column{EnvironmentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "environmentvariable_environment_id_key",
				Unique:  true,
				Columns: []*schema.Column{EnvironmentVariablesColumns[8], EnvironmentVariablesColumns[1]},
			},
			{
				Name:    "environmentvariable_environment_id_sort_order",
				Unique:  false,
				Columns: []*schema.Column{EnvironmentVariablesColumns[8], EnvironmentVariablesColumns[5]},
			},
		},
	}
	// FoldersColumns holds the columns for the "folders" table.
	FoldersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "parent_id", Type: field.TypeUUID, Nullable: true},
	}
	// FoldersTable holds the schema information for the "folders" table.
	FoldersTable = &schema.Table{
		Name:       "folders",
		Columns:    FoldersColumns,
		PrimaryKey: []*schema.Column{FoldersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "folders_folders_children",
				Columns:    []*schema.Column{FoldersColumns[5]},
				RefColumns: []*schema.Column{FoldersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "folder_parent_id_name",
				Unique:  true,
				Columns: []*schema.Column{FoldersColumns[5], FoldersColumns[1]},
			},
		},
	}
	// HistoriesColumns holds the columns for the "histories" table.
	HistoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "method", Type: field.TypeString},
		{Name: "url", Type: field.TypeString, Size: 2147483647},
		{Name: "status_code", Type: field.TypeInt},
		{Name: "duration_ms", Type: field.TypeInt, Nullable: true},
		{Name: "response_size_bytes", Type: field.TypeInt, Nullable: true},
		{Name: "request_headers_json", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "response_headers_json", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "request_body", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "response_body", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "root_folder_id", Type: field.TypeUUID, Nullable: true},
		{Name: "request_id", Type: field.TypeUUID, Nullable: true},
	}
	// HistoriesTable holds the schema information for the "histories" table.
	HistoriesTable = &schema.Table{
		Name:       "histories",
		Columns:    HistoriesColumns,
		PrimaryKey: []*schema.Column{HistoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "histories_folders_histories",
				Columns:    []*schema.Column{HistoriesColumns[11]},
				RefColumns: []*schema.Column{FoldersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "histories_requests_histories",
				Columns:    []*schema.Column{HistoriesColumns[12]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RequestsColumns holds the columns for the "requests" table.
	RequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "method", Type: field.TypeString, Default: "GET"},
		{Name: "url", Type: field.TypeString, Size: 2147483647},
		{Name: "body_mode", Type: field.TypeString},
		{Name: "raw_body", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "auth_json", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "insecure_skip_verify", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "folder_id", Type: field.TypeUUID},
	}
	// RequestsTable holds the schema information for the "requests" table.
	RequestsTable = &schema.Table{
		Name:       "requests",
		Columns:    RequestsColumns,
		PrimaryKey: []*schema.Column{RequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "requests_folders_requests",
				Columns:    []*schema.Column{RequestsColumns[10]},
				RefColumns: []*schema.Column{FoldersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "request_folder_id_name",
				Unique:  true,
				Columns: []*schema.Column{RequestsColumns[10], RequestsColumns[1]},
			},
		},
	}
	// RequestAssertionsColumns holds the columns for the "request_assertions" table.
	RequestAssertionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "source", Type: field.TypeString},
		{Name: "expression", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "operator", Type: field.TypeString},
		{Name: "expected", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "request_id", Type: field.TypeUUID},
	}
	// RequestAssertionsTable holds the schema information for the "request_assertions" table.
	RequestAssertionsTable = &schema.Table{
		Name:       "request_assertions",
		Columns:    RequestAssertionsColumns,
		PrimaryKey: []*schema.Column{RequestAssertionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "request_assertions_requests_request_assertions",
				Columns:    []*schema.Column{RequestAssertionsColumns[10]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "requestassertion_request_id_sort_order",
				Unique:  false,
				Columns: []*schema.Column{RequestAssertionsColumns[10], RequestAssertionsColumns[7]},
			},
		},
	}
	// RequestCapturesColumns holds the columns for the "request_captures" table.
	RequestCapturesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString},
		{Name: "source", Type: field.TypeString},
		{Name: "expression", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "target_scope", Type: field.TypeString, Default: "environment"},
		{Name: "target_variable", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "request_id", Type: field.TypeUUID},
	}
	// RequestCapturesTable holds the schema information for the "request_captures" table.
	RequestCapturesTable = &schema.Table{
		Name:       "request_captures",
		Columns:    RequestCapturesColumns,
		PrimaryKey: []*schema.Column{RequestCapturesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "request_captures_requests_request_captures",
				Columns:    []*schema.Column{RequestCapturesColumns[10]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "requestcapture_request_id_sort_order",
				Unique:  false,
				Columns: []*schema.Column{RequestCapturesColumns[10], RequestCapturesColumns[7]},
			},
		},
	}
	// RequestFormFieldsColumns holds the columns for the "request_form_fields" table.
	RequestFormFieldsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "field_kind", Type: field.TypeString},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "request_id", Type: field.TypeUUID},
	}
	// RequestFormFieldsTable holds the schema information for the "request_form_fields" table.
	RequestFormFieldsTable = &schema.Table{
		Name:       "request_form_fields",
		Columns:    RequestFormFieldsColumns,
		PrimaryKey: []*schema.Column{RequestFormFieldsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "request_form_fields_requests_request_form_fields",
				Columns:    []*schema.Column{RequestFormFieldsColumns[6]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "requestformfield_request_id_sort_order",
				Unique:  false,
				Columns: []*schema.Column{RequestFormFieldsColumns[6], RequestFormFieldsColumns[5]},
			},
		},
	}
	// RequestHeadersColumns holds the columns for the "request_headers" table.
	RequestHeadersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString, Size: 2147483647},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "request_id", Type: field.TypeUUID},
	}
	// RequestHeadersTable holds the schema information for the "request_headers" table.
	RequestHeadersTable = &schema.Table{
		Name:       "request_headers",
		Columns:    RequestHeadersColumns,
		PrimaryKey: []*schema.Column{RequestHeadersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "request_headers_requests_request_headers",
				Columns:    []*schema.Column{RequestHeadersColumns[5]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "requestheader_request_id_sort_order",
				Unique:  false,
				Columns: []*schema.Column{RequestHeadersColumns[5], RequestHeadersColumns[4]},
			},
		},
	}
	// RequestQueryParamsColumns holds the columns for the "request_query_params" table.
	RequestQueryParamsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString},
		{Name: "value", Type: field.TypeString, Size: 2147483647},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "request_id", Type: field.TypeUUID},
	}
	// RequestQueryParamsTable holds the schema information for the "request_query_params" table.
	RequestQueryParamsTable = &schema.Table{
		Name:       "request_query_params",
		Columns:    RequestQueryParamsColumns,
		PrimaryKey: []*schema.Column{RequestQueryParamsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "request_query_params_requests_request_query_params",
				Columns:    []*schema.Column{RequestQueryParamsColumns[5]},
				RefColumns: []*schema.Column{RequestsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "requestqueryparam_request_id_sort_order",
				Unique:  false,
				Columns: []*schema.Column{RequestQueryParamsColumns[5], RequestQueryParamsColumns[4]},
			},
		},
	}
	// RunnerRunsColumns holds the columns for the "runner_runs" table.
	RunnerRunsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "folder_id", Type: field.TypeUUID, Nullable: true},
		{Name: "environment_id", Type: field.TypeUUID, Nullable: true},
		{Name: "folder_name", Type: field.TypeString, Default: ""},
		{Name: "environment_name", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "running"},
		{Name: "total_count", Type: field.TypeInt, Default: 0},
		{Name: "passed_count", Type: field.TypeInt, Default: 0},
		{Name: "failed_count", Type: field.TypeInt, Default: 0},
		{Name: "error_count", Type: field.TypeInt, Default: 0},
		{Name: "duration_ms", Type: field.TypeInt, Default: 0},
		{Name: "notes", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "started_at", Type: field.TypeTime},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
	}
	// RunnerRunsTable holds the schema information for the "runner_runs" table.
	RunnerRunsTable = &schema.Table{
		Name:       "runner_runs",
		Columns:    RunnerRunsColumns,
		PrimaryKey: []*schema.Column{RunnerRunsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "runnerrun_started_at",
				Unique:  false,
				Columns: []*schema.Column{RunnerRunsColumns[12]},
			},
		},
	}
	// RunnerRunRequestsColumns holds the columns for the "runner_run_requests" table.
	RunnerRunRequestsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "request_id", Type: field.TypeUUID, Nullable: true},
		{Name: "request_name", Type: field.TypeString, Default: ""},
		{Name: "method", Type: field.TypeString, Default: "GET"},
		{Name: "url", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "passed"},
		{Name: "status_code", Type: field.TypeInt, Default: 0},
		{Name: "duration_ms", Type: field.TypeInt, Default: 0},
		{Name: "response_size_bytes", Type: field.TypeInt, Default: 0},
		{Name: "error_message", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "assertions_json", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "captures_json", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "request_headers_json", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "response_headers_json", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "request_body", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "response_body", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "body_truncated", Type: field.TypeBool, Default: false},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "run_id", Type: field.TypeUUID},
	}
	// RunnerRunRequestsTable holds the schema information for the "runner_run_requests" table.
	RunnerRunRequestsTable = &schema.Table{
		Name:       "runner_run_requests",
		Columns:    RunnerRunRequestsColumns,
		PrimaryKey: []*schema.Column{RunnerRunRequestsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "runner_run_requests_runner_runs_requests",
				Columns:    []*schema.Column{RunnerRunRequestsColumns[19]},
				RefColumns: []*schema.Column{RunnerRunsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "runnerrunrequest_run_id_sort_order",
				Unique:  false,
				Columns: []*schema.Column{RunnerRunRequestsColumns[19], RunnerRunRequestsColumns[17]},
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
	}
	// TrustedCasColumns holds the columns for the "trusted_cas" table.
	TrustedCasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "label", Type: field.TypeString},
		{Name: "pem_content", Type: field.TypeString, Size: 2147483647},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// TrustedCasTable holds the schema information for the "trusted_cas" table.
	TrustedCasTable = &schema.Table{
		Name:       "trusted_cas",
		Columns:    TrustedCasColumns,
		PrimaryKey: []*schema.Column{TrustedCasColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "trustedca_label",
				Unique:  false,
				Columns: []*schema.Column{TrustedCasColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EnvironmentsTable,
		EnvironmentVariablesTable,
		FoldersTable,
		HistoriesTable,
		RequestsTable,
		RequestAssertionsTable,
		RequestCapturesTable,
		RequestFormFieldsTable,
		RequestHeadersTable,
		RequestQueryParamsTable,
		RunnerRunsTable,
		RunnerRunRequestsTable,
		SettingsTable,
		TrustedCasTable,
	}
)

func init() {
	EnvironmentVariablesTable.ForeignKeys[0].RefTable = EnvironmentsTable
	FoldersTable.ForeignKeys[0].RefTable = FoldersTable
	HistoriesTable.ForeignKeys[0].RefTable = FoldersTable
	HistoriesTable.ForeignKeys[1].RefTable = RequestsTable
	RequestsTable.ForeignKeys[0].RefTable = FoldersTable
	RequestAssertionsTable.ForeignKeys[0].RefTable = RequestsTable
	RequestCapturesTable.ForeignKeys[0].RefTable = RequestsTable
	RequestFormFieldsTable.ForeignKeys[0].RefTable = RequestsTable
	RequestHeadersTable.ForeignKeys[0].RefTable = RequestsTable
	RequestQueryParamsTable.ForeignKeys[0].RefTable = RequestsTable
	RunnerRunRequestsTable.ForeignKeys[0].RefTable = RunnerRunsTable
}
