// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PostmanJanai/ent/history"
	"PostmanJanai/ent/predicate"
	"PostmanJanai/ent/request"
	"PostmanJanai/ent/workspace"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// HistoryUpdate is the builder for updating History entities.
type HistoryUpdate struct {
	config
	hooks    []Hook
	mutation *HistoryMutation
}

// Where appends a list predicates to the HistoryUpdate builder.
func (_u *HistoryUpdate) Where(ps ...predicate.History) *HistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *HistoryUpdate) SetWorkspaceID(v uuid.UUID) *HistoryUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableWorkspaceID(v *uuid.UUID) *HistoryUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// ClearWorkspaceID clears the value of the "workspace_id" field.
func (_u *HistoryUpdate) ClearWorkspaceID() *HistoryUpdate {
	_u.mutation.ClearWorkspaceID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *HistoryUpdate) SetRequestID(v uuid.UUID) *HistoryUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableRequestID(v *uuid.UUID) *HistoryUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *HistoryUpdate) ClearRequestID() *HistoryUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetMethod sets the "method" field.
func (_u *HistoryUpdate) SetMethod(v string) *HistoryUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableMethod(v *string) *HistoryUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *HistoryUpdate) SetURL(v string) *HistoryUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableURL(v *string) *HistoryUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *HistoryUpdate) SetStatusCode(v int) *HistoryUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableStatusCode(v *int) *HistoryUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *HistoryUpdate) AddStatusCode(v int) *HistoryUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *HistoryUpdate) SetDurationMs(v int) *HistoryUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableDurationMs(v *int) *HistoryUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *HistoryUpdate) AddDurationMs(v int) *HistoryUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *HistoryUpdate) ClearDurationMs() *HistoryUpdate {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetResponseSizeBytes sets the "response_size_bytes" field.
func (_u *HistoryUpdate) SetResponseSizeBytes(v int) *HistoryUpdate {
	_u.mutation.ResetResponseSizeBytes()
	_u.mutation.SetResponseSizeBytes(v)
	return _u
}

// SetNillableResponseSizeBytes sets the "response_size_bytes" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableResponseSizeBytes(v *int) *HistoryUpdate {
	if v != nil {
		_u.SetResponseSizeBytes(*v)
	}
	return _u
}

// AddResponseSizeBytes adds value to the "response_size_bytes" field.
func (_u *HistoryUpdate) AddResponseSizeBytes(v int) *HistoryUpdate {
	_u.mutation.AddResponseSizeBytes(v)
	return _u
}

// ClearResponseSizeBytes clears the value of the "response_size_bytes" field.
func (_u *HistoryUpdate) ClearResponseSizeBytes() *HistoryUpdate {
	_u.mutation.ClearResponseSizeBytes()
	return _u
}

// SetRequestHeadersJSON sets the "request_headers_json" field.
func (_u *HistoryUpdate) SetRequestHeadersJSON(v string) *HistoryUpdate {
	_u.mutation.SetRequestHeadersJSON(v)
	return _u
}

// SetNillableRequestHeadersJSON sets the "request_headers_json" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableRequestHeadersJSON(v *string) *HistoryUpdate {
	if v != nil {
		_u.SetRequestHeadersJSON(*v)
	}
	return _u
}

// ClearRequestHeadersJSON clears the value of the "request_headers_json" field.
func (_u *HistoryUpdate) ClearRequestHeadersJSON() *HistoryUpdate {
	_u.mutation.ClearRequestHeadersJSON()
	return _u
}

// SetResponseHeadersJSON sets the "response_headers_json" field.
func (_u *HistoryUpdate) SetResponseHeadersJSON(v string) *HistoryUpdate {
	_u.mutation.SetResponseHeadersJSON(v)
	return _u
}

// SetNillableResponseHeadersJSON sets the "response_headers_json" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableResponseHeadersJSON(v *string) *HistoryUpdate {
	if v != nil {
		_u.SetResponseHeadersJSON(*v)
	}
	return _u
}

// ClearResponseHeadersJSON clears the value of the "response_headers_json" field.
func (_u *HistoryUpdate) ClearResponseHeadersJSON() *HistoryUpdate {
	_u.mutation.ClearResponseHeadersJSON()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *HistoryUpdate) SetRequestBody(v string) *HistoryUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableRequestBody(v *string) *HistoryUpdate {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *HistoryUpdate) ClearRequestBody() *HistoryUpdate {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *HistoryUpdate) SetResponseBody(v string) *HistoryUpdate {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *HistoryUpdate) SetNillableResponseBody(v *string) *HistoryUpdate {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *HistoryUpdate) ClearResponseBody() *HistoryUpdate {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *HistoryUpdate) SetWorkspace(v *Workspace) *HistoryUpdate {
	return _u.SetWorkspaceID(v.ID)
}

// SetRequest sets the "request" edge to the Request entity.
func (_u *HistoryUpdate) SetRequest(v *Request) *HistoryUpdate {
	return _u.SetRequestID(v.ID)
}

// Mutation returns the HistoryMutation object of the builder.
func (_u *HistoryUpdate) Mutation() *HistoryMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *HistoryUpdate) ClearWorkspace() *HistoryUpdate {
	_u.mutation.ClearWorkspace()
	return _u
}

// ClearRequest clears the "request" edge to the Request entity.
func (_u *HistoryUpdate) ClearRequest() *HistoryUpdate {
	_u.mutation.ClearRequest()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *HistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *HistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HistoryUpdate) check() error {
	if v, ok := _u.mutation.Method(); ok {
		if err := history.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "History.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := history.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "History.url": %w`, err)}
		}
	}
	return nil
}

func (_u *HistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(history.Table, history.Columns, sqlgraph.NewFieldSpec(history.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(history.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(history.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(history.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(history.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(history.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(history.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(history.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ResponseSizeBytes(); ok {
		_spec.SetField(history.FieldResponseSizeBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseSizeBytes(); ok {
		_spec.AddField(history.FieldResponseSizeBytes, field.TypeInt, value)
	}
	if _u.mutation.ResponseSizeBytesCleared() {
		_spec.ClearField(history.FieldResponseSizeBytes, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestHeadersJSON(); ok {
		_spec.SetField(history.FieldRequestHeadersJSON, field.TypeString, value)
	}
	if _u.mutation.RequestHeadersJSONCleared() {
		_spec.ClearField(history.FieldRequestHeadersJSON, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseHeadersJSON(); ok {
		_spec.SetField(history.FieldResponseHeadersJSON, field.TypeString, value)
	}
	if _u.mutation.ResponseHeadersJSONCleared() {
		_spec.ClearField(history.FieldResponseHeadersJSON, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(history.FieldRequestBody, field.TypeString, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(history.FieldRequestBody, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(history.FieldResponseBody, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(history.FieldResponseBody, field.TypeString)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.WorkspaceTable,
			Columns: []string{history.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.WorkspaceTable,
			Columns: []string{history.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.RequestTable,
			Columns: []string{history.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.RequestTable,
			Columns: []string{history.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{history.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// HistoryUpdateOne is the builder for updating a single History entity.
type HistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *HistoryMutation
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *HistoryUpdateOne) SetWorkspaceID(v uuid.UUID) *HistoryUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableWorkspaceID(v *uuid.UUID) *HistoryUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// ClearWorkspaceID clears the value of the "workspace_id" field.
func (_u *HistoryUpdateOne) ClearWorkspaceID() *HistoryUpdateOne {
	_u.mutation.ClearWorkspaceID()
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *HistoryUpdateOne) SetRequestID(v uuid.UUID) *HistoryUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableRequestID(v *uuid.UUID) *HistoryUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *HistoryUpdateOne) ClearRequestID() *HistoryUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetMethod sets the "method" field.
func (_u *HistoryUpdateOne) SetMethod(v string) *HistoryUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableMethod(v *string) *HistoryUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *HistoryUpdateOne) SetURL(v string) *HistoryUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableURL(v *string) *HistoryUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *HistoryUpdateOne) SetStatusCode(v int) *HistoryUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableStatusCode(v *int) *HistoryUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *HistoryUpdateOne) AddStatusCode(v int) *HistoryUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *HistoryUpdateOne) SetDurationMs(v int) *HistoryUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableDurationMs(v *int) *HistoryUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *HistoryUpdateOne) AddDurationMs(v int) *HistoryUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (_u *HistoryUpdateOne) ClearDurationMs() *HistoryUpdateOne {
	_u.mutation.ClearDurationMs()
	return _u
}

// SetResponseSizeBytes sets the "response_size_bytes" field.
func (_u *HistoryUpdateOne) SetResponseSizeBytes(v int) *HistoryUpdateOne {
	_u.mutation.ResetResponseSizeBytes()
	_u.mutation.SetResponseSizeBytes(v)
	return _u
}

// SetNillableResponseSizeBytes sets the "response_size_bytes" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableResponseSizeBytes(v *int) *HistoryUpdateOne {
	if v != nil {
		_u.SetResponseSizeBytes(*v)
	}
	return _u
}

// AddResponseSizeBytes adds value to the "response_size_bytes" field.
func (_u *HistoryUpdateOne) AddResponseSizeBytes(v int) *HistoryUpdateOne {
	_u.mutation.AddResponseSizeBytes(v)
	return _u
}

// ClearResponseSizeBytes clears the value of the "response_size_bytes" field.
func (_u *HistoryUpdateOne) ClearResponseSizeBytes() *HistoryUpdateOne {
	_u.mutation.ClearResponseSizeBytes()
	return _u
}

// SetRequestHeadersJSON sets the "request_headers_json" field.
func (_u *HistoryUpdateOne) SetRequestHeadersJSON(v string) *HistoryUpdateOne {
	_u.mutation.SetRequestHeadersJSON(v)
	return _u
}

// SetNillableRequestHeadersJSON sets the "request_headers_json" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableRequestHeadersJSON(v *string) *HistoryUpdateOne {
	if v != nil {
		_u.SetRequestHeadersJSON(*v)
	}
	return _u
}

// ClearRequestHeadersJSON clears the value of the "request_headers_json" field.
func (_u *HistoryUpdateOne) ClearRequestHeadersJSON() *HistoryUpdateOne {
	_u.mutation.ClearRequestHeadersJSON()
	return _u
}

// SetResponseHeadersJSON sets the "response_headers_json" field.
func (_u *HistoryUpdateOne) SetResponseHeadersJSON(v string) *HistoryUpdateOne {
	_u.mutation.SetResponseHeadersJSON(v)
	return _u
}

// SetNillableResponseHeadersJSON sets the "response_headers_json" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableResponseHeadersJSON(v *string) *HistoryUpdateOne {
	if v != nil {
		_u.SetResponseHeadersJSON(*v)
	}
	return _u
}

// ClearResponseHeadersJSON clears the value of the "response_headers_json" field.
func (_u *HistoryUpdateOne) ClearResponseHeadersJSON() *HistoryUpdateOne {
	_u.mutation.ClearResponseHeadersJSON()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *HistoryUpdateOne) SetRequestBody(v string) *HistoryUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableRequestBody(v *string) *HistoryUpdateOne {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *HistoryUpdateOne) ClearRequestBody() *HistoryUpdateOne {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *HistoryUpdateOne) SetResponseBody(v string) *HistoryUpdateOne {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *HistoryUpdateOne) SetNillableResponseBody(v *string) *HistoryUpdateOne {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *HistoryUpdateOne) ClearResponseBody() *HistoryUpdateOne {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *HistoryUpdateOne) SetWorkspace(v *Workspace) *HistoryUpdateOne {
	return _u.SetWorkspaceID(v.ID)
}

// SetRequest sets the "request" edge to the Request entity.
func (_u *HistoryUpdateOne) SetRequest(v *Request) *HistoryUpdateOne {
	return _u.SetRequestID(v.ID)
}

// Mutation returns the HistoryMutation object of the builder.
func (_u *HistoryUpdateOne) Mutation() *HistoryMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *HistoryUpdateOne) ClearWorkspace() *HistoryUpdateOne {
	_u.mutation.ClearWorkspace()
	return _u
}

// ClearRequest clears the "request" edge to the Request entity.
func (_u *HistoryUpdateOne) ClearRequest() *HistoryUpdateOne {
	_u.mutation.ClearRequest()
	return _u
}

// Where appends a list predicates to the HistoryUpdate builder.
func (_u *HistoryUpdateOne) Where(ps ...predicate.History) *HistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *HistoryUpdateOne) Select(field string, fields ...string) *HistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated History entity.
func (_u *HistoryUpdateOne) Save(ctx context.Context) (*History, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *HistoryUpdateOne) SaveX(ctx context.Context) *History {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *HistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *HistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *HistoryUpdateOne) check() error {
	if v, ok := _u.mutation.Method(); ok {
		if err := history.MethodValidator(v); err != nil {
			return &ValidationError{Name: "method", err: fmt.Errorf(`ent: validator failed for field "History.method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := history.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "History.url": %w`, err)}
		}
	}
	return nil
}

func (_u *HistoryUpdateOne) sqlSave(ctx context.Context) (_node *History, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(history.Table, history.Columns, sqlgraph.NewFieldSpec(history.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "History.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, history.FieldID)
		for _, f := range fields {
			if !history.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != history.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(history.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(history.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(history.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(history.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(history.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(history.FieldDurationMs, field.TypeInt, value)
	}
	if _u.mutation.DurationMsCleared() {
		_spec.ClearField(history.FieldDurationMs, field.TypeInt)
	}
	if value, ok := _u.mutation.ResponseSizeBytes(); ok {
		_spec.SetField(history.FieldResponseSizeBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseSizeBytes(); ok {
		_spec.AddField(history.FieldResponseSizeBytes, field.TypeInt, value)
	}
	if _u.mutation.ResponseSizeBytesCleared() {
		_spec.ClearField(history.FieldResponseSizeBytes, field.TypeInt)
	}
	if value, ok := _u.mutation.RequestHeadersJSON(); ok {
		_spec.SetField(history.FieldRequestHeadersJSON, field.TypeString, value)
	}
	if _u.mutation.RequestHeadersJSONCleared() {
		_spec.ClearField(history.FieldRequestHeadersJSON, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseHeadersJSON(); ok {
		_spec.SetField(history.FieldResponseHeadersJSON, field.TypeString, value)
	}
	if _u.mutation.ResponseHeadersJSONCleared() {
		_spec.ClearField(history.FieldResponseHeadersJSON, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(history.FieldRequestBody, field.TypeString, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(history.FieldRequestBody, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(history.FieldResponseBody, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(history.FieldResponseBody, field.TypeString)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.WorkspaceTable,
			Columns: []string{history.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.WorkspaceTable,
			Columns: []string{history.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.RequestTable,
			Columns: []string{history.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   history.RequestTable,
			Columns: []string{history.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &History{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{history.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
