// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PostmanJanai/ent/request"
	"PostmanJanai/ent/requestcapture"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// RequestCapture is the model entity for the RequestCapture schema.
type RequestCapture struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID uuid.UUID `json:"request_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// Expression holds the value of the "expression" field.
	Expression string `json:"expression,omitempty"`
	// TargetScope holds the value of the "target_scope" field.
	TargetScope string `json:"target_scope,omitempty"`
	// TargetVariable holds the value of the "target_variable" field.
	TargetVariable string `json:"target_variable,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RequestCaptureQuery when eager-loading is set.
	Edges        RequestCaptureEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RequestCaptureEdges holds the relations/edges for other nodes in the graph.
type RequestCaptureEdges struct {
	// Request holds the value of the request edge.
	Request *Request `json:"request,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RequestOrErr returns the Request value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestCaptureEdges) RequestOrErr() (*Request, error) {
	if e.Request != nil {
		return e.Request, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: request.Label}
	}
	return nil, &NotLoadedError{edge: "request"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestCapture) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestcapture.FieldEnabled:
			values[i] = new(sql.NullBool)
		case requestcapture.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case requestcapture.FieldName, requestcapture.FieldSource, requestcapture.FieldExpression, requestcapture.FieldTargetScope, requestcapture.FieldTargetVariable:
			values[i] = new(sql.NullString)
		case requestcapture.FieldCreatedAt, requestcapture.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case requestcapture.FieldID, requestcapture.FieldRequestID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestCapture fields.
func (_m *RequestCapture) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestcapture.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case requestcapture.FieldRequestID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value != nil {
				_m.RequestID = *value
			}
		case requestcapture.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case requestcapture.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case requestcapture.FieldExpression:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field expression", values[i])
			} else if value.Valid {
				_m.Expression = value.String
			}
		case requestcapture.FieldTargetScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_scope", values[i])
			} else if value.Valid {
				_m.TargetScope = value.String
			}
		case requestcapture.FieldTargetVariable:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_variable", values[i])
			} else if value.Valid {
				_m.TargetVariable = value.String
			}
		case requestcapture.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case requestcapture.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case requestcapture.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case requestcapture.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RequestCapture.
// This includes values selected through modifiers, order, etc.
func (_m *RequestCapture) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRequest queries the "request" edge of the RequestCapture entity.
func (_m *RequestCapture) QueryRequest() *RequestQuery {
	return NewRequestCaptureClient(_m.config).QueryRequest(_m)
}

// Update returns a builder for updating this RequestCapture.
// Note that you need to call RequestCapture.Unwrap() before calling this method if this RequestCapture
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequestCapture) Update() *RequestCaptureUpdateOne {
	return NewRequestCaptureClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequestCapture entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequestCapture) Unwrap() *RequestCapture {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestCapture is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequestCapture) String() string {
	var builder strings.Builder
	builder.WriteString("RequestCapture(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestID))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	builder.WriteString("expression=")
	builder.WriteString(_m.Expression)
	builder.WriteString(", ")
	builder.WriteString("target_scope=")
	builder.WriteString(_m.TargetScope)
	builder.WriteString(", ")
	builder.WriteString("target_variable=")
	builder.WriteString(_m.TargetVariable)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RequestCaptures is a parsable slice of RequestCapture.
type RequestCaptures []*RequestCapture
