// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PostmanJanai/ent/collection"
	"PostmanJanai/ent/history"
	"PostmanJanai/ent/predicate"
	"PostmanJanai/ent/request"
	"PostmanJanai/ent/requestformfield"
	"PostmanJanai/ent/requestheader"
	"PostmanJanai/ent/requestqueryparam"
	"PostmanJanai/ent/workspace"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RequestUpdate is the builder for updating Request entities.
type RequestUpdate struct {
	config
	hooks    []Hook
	mutation *RequestMutation
}

// Where appends a list predicates to the RequestUpdate builder.
func (_u *RequestUpdate) Where(ps ...predicate.Request) *RequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *RequestUpdate) SetWorkspaceID(v uuid.UUID) *RequestUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableWorkspaceID(v *uuid.UUID) *RequestUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *RequestUpdate) SetCollectionID(v uuid.UUID) *RequestUpdate {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableCollectionID(v *uuid.UUID) *RequestUpdate {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// ClearCollectionID clears the value of the "collection_id" field.
func (_u *RequestUpdate) ClearCollectionID() *RequestUpdate {
	_u.mutation.ClearCollectionID()
	return _u
}

// SetName sets the "name" field.
func (_u *RequestUpdate) SetName(v string) *RequestUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableName(v *string) *RequestUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *RequestUpdate) SetMethod(v string) *RequestUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableMethod(v *string) *RequestUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *RequestUpdate) SetURL(v string) *RequestUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableURL(v *string) *RequestUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetBodyMode sets the "body_mode" field.
func (_u *RequestUpdate) SetBodyMode(v string) *RequestUpdate {
	_u.mutation.SetBodyMode(v)
	return _u
}

// SetNillableBodyMode sets the "body_mode" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableBodyMode(v *string) *RequestUpdate {
	if v != nil {
		_u.SetBodyMode(*v)
	}
	return _u
}

// SetRawBody sets the "raw_body" field.
func (_u *RequestUpdate) SetRawBody(v string) *RequestUpdate {
	_u.mutation.SetRawBody(v)
	return _u
}

// SetNillableRawBody sets the "raw_body" field if the given value is not nil.
func (_u *RequestUpdate) SetNillableRawBody(v *string) *RequestUpdate {
	if v != nil {
		_u.SetRawBody(*v)
	}
	return _u
}

// ClearRawBody clears the value of the "raw_body" field.
func (_u *RequestUpdate) ClearRawBody() *RequestUpdate {
	_u.mutation.ClearRawBody()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestUpdate) SetUpdatedAt(v time.Time) *RequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *RequestUpdate) SetWorkspace(v *Workspace) *RequestUpdate {
	return _u.SetWorkspaceID(v.ID)
}

// SetCollection sets the "collection" edge to the Collection entity.
func (_u *RequestUpdate) SetCollection(v *Collection) *RequestUpdate {
	return _u.SetCollectionID(v.ID)
}

// AddRequestHeaderIDs adds the "request_headers" edge to the RequestHeader entity by IDs.
func (_u *RequestUpdate) AddRequestHeaderIDs(ids ...uuid.UUID) *RequestUpdate {
	_u.mutation.AddRequestHeaderIDs(ids...)
	return _u
}

// AddRequestHeaders adds the "request_headers" edges to the RequestHeader entity.
func (_u *RequestUpdate) AddRequestHeaders(v ...*RequestHeader) *RequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestHeaderIDs(ids...)
}

// AddRequestQueryParamIDs adds the "request_query_params" edge to the RequestQueryParam entity by IDs.
func (_u *RequestUpdate) AddRequestQueryParamIDs(ids ...uuid.UUID) *RequestUpdate {
	_u.mutation.AddRequestQueryParamIDs(ids...)
	return _u
}

// AddRequestQueryParams adds the "request_query_params" edges to the RequestQueryParam entity.
func (_u *RequestUpdate) AddRequestQueryParams(v ...*RequestQueryParam) *RequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestQueryParamIDs(ids...)
}

// AddRequestFormFieldIDs adds the "request_form_fields" edge to the RequestFormField entity by IDs.
func (_u *RequestUpdate) AddRequestFormFieldIDs(ids ...uuid.UUID) *RequestUpdate {
	_u.mutation.AddRequestFormFieldIDs(ids...)
	return _u
}

// AddRequestFormFields adds the "request_form_fields" edges to the RequestFormField entity.
func (_u *RequestUpdate) AddRequestFormFields(v ...*RequestFormField) *RequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestFormFieldIDs(ids...)
}

// AddHistoryIDs adds the "histories" edge to the History entity by IDs.
func (_u *RequestUpdate) AddHistoryIDs(ids ...uuid.UUID) *RequestUpdate {
	_u.mutation.AddHistoryIDs(ids...)
	return _u
}

// AddHistories adds the "histories" edges to the History entity.
func (_u *RequestUpdate) AddHistories(v ...*History) *RequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHistoryIDs(ids...)
}

// Mutation returns the RequestMutation object of the builder.
func (_u *RequestUpdate) Mutation() *RequestMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *RequestUpdate) ClearWorkspace() *RequestUpdate {
	_u.mutation.ClearWorkspace()
	return _u
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (_u *RequestUpdate) ClearCollection() *RequestUpdate {
	_u.mutation.ClearCollection()
	return _u
}

// ClearRequestHeaders clears all "request_headers" edges to the RequestHeader entity.
func (_u *RequestUpdate) ClearRequestHeaders() *RequestUpdate {
	_u.mutation.ClearRequestHeaders()
	return _u
}

// RemoveRequestHeaderIDs removes the "request_headers" edge to RequestHeader entities by IDs.
func (_u *RequestUpdate) RemoveRequestHeaderIDs(ids ...uuid.UUID) *RequestUpdate {
	_u.mutation.RemoveRequestHeaderIDs(ids...)
	return _u
}

// RemoveRequestHeaders removes "request_headers" edges to RequestHeader entities.
func (_u *RequestUpdate) RemoveRequestHeaders(v ...*RequestHeader) *RequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestHeaderIDs(ids...)
}

// ClearRequestQueryParams clears all "request_query_params" edges to the RequestQueryParam entity.
func (_u *RequestUpdate) ClearRequestQueryParams() *RequestUpdate {
	_u.mutation.ClearRequestQueryParams()
	return _u
}

// RemoveRequestQueryParamIDs removes the "request_query_params" edge to RequestQueryParam entities by IDs.
func (_u *RequestUpdate) RemoveRequestQueryParamIDs(ids ...uuid.UUID) *RequestUpdate {
	_u.mutation.RemoveRequestQueryParamIDs(ids...)
	return _u
}

// RemoveRequestQueryParams removes "request_query_params" edges to RequestQueryParam entities.
func (_u *RequestUpdate) RemoveRequestQueryParams(v ...*RequestQueryParam) *RequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestQueryParamIDs(ids...)
}

// ClearRequestFormFields clears all "request_form_fields" edges to the RequestFormField entity.
func (_u *RequestUpdate) ClearRequestFormFields() *RequestUpdate {
	_u.mutation.ClearRequestFormFields()
	return _u
}

// RemoveRequestFormFieldIDs removes the "request_form_fields" edge to RequestFormField entities by IDs.
func (_u *RequestUpdate) RemoveRequestFormFieldIDs(ids ...uuid.UUID) *RequestUpdate {
	_u.mutation.RemoveRequestFormFieldIDs(ids...)
	return _u
}

// RemoveRequestFormFields removes "request_form_fields" edges to RequestFormField entities.
func (_u *RequestUpdate) RemoveRequestFormFields(v ...*RequestFormField) *RequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestFormFieldIDs(ids...)
}

// ClearHistories clears all "histories" edges to the History entity.
func (_u *RequestUpdate) ClearHistories() *RequestUpdate {
	_u.mutation.ClearHistories()
	return _u
}

// RemoveHistoryIDs removes the "histories" edge to History entities by IDs.
func (_u *RequestUpdate) RemoveHistoryIDs(ids ...uuid.UUID) *RequestUpdate {
	_u.mutation.RemoveHistoryIDs(ids...)
	return _u
}

// RemoveHistories removes "histories" edges to History entities.
func (_u *RequestUpdate) RemoveHistories(v ...*History) *RequestUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHistoryIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := request.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := request.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Request.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := request.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Request.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BodyMode(); ok {
		if err := request.BodyModeValidator(v); err != nil {
			return &ValidationError{Name: "body_mode", err: fmt.Errorf(`ent: validator failed for field "Request.body_mode": %w`, err)}
		}
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Request.workspace"`)
	}
	return nil
}

func (_u *RequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(request.Table, request.Columns, sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(request.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(request.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(request.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodyMode(); ok {
		_spec.SetField(request.FieldBodyMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawBody(); ok {
		_spec.SetField(request.FieldRawBody, field.TypeString, value)
	}
	if _u.mutation.RawBodyCleared() {
		_spec.ClearField(request.FieldRawBody, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(request.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.WorkspaceTable,
			Columns: []string{request.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.WorkspaceTable,
			Columns: []string{request.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.CollectionTable,
			Columns: []string{request.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.CollectionTable,
			Columns: []string{request.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestHeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestHeadersTable,
			Columns: []string{request.RequestHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestheader.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestHeadersIDs(); len(nodes) > 0 && !_u.mutation.RequestHeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestHeadersTable,
			Columns: []string{request.RequestHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestheader.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestHeadersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestHeadersTable,
			Columns: []string{request.RequestHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestheader.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestQueryParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestQueryParamsTable,
			Columns: []string{request.RequestQueryParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestqueryparam.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestQueryParamsIDs(); len(nodes) > 0 && !_u.mutation.RequestQueryParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestQueryParamsTable,
			Columns: []string{request.RequestQueryParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestqueryparam.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestQueryParamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestQueryParamsTable,
			Columns: []string{request.RequestQueryParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestqueryparam.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestFormFieldsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestFormFieldsTable,
			Columns: []string{request.RequestFormFieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestformfield.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestFormFieldsIDs(); len(nodes) > 0 && !_u.mutation.RequestFormFieldsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestFormFieldsTable,
			Columns: []string{request.RequestFormFieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestformfield.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestFormFieldsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestFormFieldsTable,
			Columns: []string{request.RequestFormFieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestformfield.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.HistoriesTable,
			Columns: []string{request.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHistoriesIDs(); len(nodes) > 0 && !_u.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.HistoriesTable,
			Columns: []string{request.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.HistoriesTable,
			Columns: []string{request.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{request.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestUpdateOne is the builder for updating a single Request entity.
type RequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestMutation
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *RequestUpdateOne) SetWorkspaceID(v uuid.UUID) *RequestUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableWorkspaceID(v *uuid.UUID) *RequestUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetCollectionID sets the "collection_id" field.
func (_u *RequestUpdateOne) SetCollectionID(v uuid.UUID) *RequestUpdateOne {
	_u.mutation.SetCollectionID(v)
	return _u
}

// SetNillableCollectionID sets the "collection_id" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableCollectionID(v *uuid.UUID) *RequestUpdateOne {
	if v != nil {
		_u.SetCollectionID(*v)
	}
	return _u
}

// ClearCollectionID clears the value of the "collection_id" field.
func (_u *RequestUpdateOne) ClearCollectionID() *RequestUpdateOne {
	_u.mutation.ClearCollectionID()
	return _u
}

// SetName sets the "name" field.
func (_u *RequestUpdateOne) SetName(v string) *RequestUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableName(v *string) *RequestUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *RequestUpdateOne) SetMethod(v string) *RequestUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableMethod(v *string) *RequestUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *RequestUpdateOne) SetURL(v string) *RequestUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableURL(v *string) *RequestUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetBodyMode sets the "body_mode" field.
func (_u *RequestUpdateOne) SetBodyMode(v string) *RequestUpdateOne {
	_u.mutation.SetBodyMode(v)
	return _u
}

// SetNillableBodyMode sets the "body_mode" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableBodyMode(v *string) *RequestUpdateOne {
	if v != nil {
		_u.SetBodyMode(*v)
	}
	return _u
}

// SetRawBody sets the "raw_body" field.
func (_u *RequestUpdateOne) SetRawBody(v string) *RequestUpdateOne {
	_u.mutation.SetRawBody(v)
	return _u
}

// SetNillableRawBody sets the "raw_body" field if the given value is not nil.
func (_u *RequestUpdateOne) SetNillableRawBody(v *string) *RequestUpdateOne {
	if v != nil {
		_u.SetRawBody(*v)
	}
	return _u
}

// ClearRawBody clears the value of the "raw_body" field.
func (_u *RequestUpdateOne) ClearRawBody() *RequestUpdateOne {
	_u.mutation.ClearRawBody()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestUpdateOne) SetUpdatedAt(v time.Time) *RequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *RequestUpdateOne) SetWorkspace(v *Workspace) *RequestUpdateOne {
	return _u.SetWorkspaceID(v.ID)
}

// SetCollection sets the "collection" edge to the Collection entity.
func (_u *RequestUpdateOne) SetCollection(v *Collection) *RequestUpdateOne {
	return _u.SetCollectionID(v.ID)
}

// AddRequestHeaderIDs adds the "request_headers" edge to the RequestHeader entity by IDs.
func (_u *RequestUpdateOne) AddRequestHeaderIDs(ids ...uuid.UUID) *RequestUpdateOne {
	_u.mutation.AddRequestHeaderIDs(ids...)
	return _u
}

// AddRequestHeaders adds the "request_headers" edges to the RequestHeader entity.
func (_u *RequestUpdateOne) AddRequestHeaders(v ...*RequestHeader) *RequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestHeaderIDs(ids...)
}

// AddRequestQueryParamIDs adds the "request_query_params" edge to the RequestQueryParam entity by IDs.
func (_u *RequestUpdateOne) AddRequestQueryParamIDs(ids ...uuid.UUID) *RequestUpdateOne {
	_u.mutation.AddRequestQueryParamIDs(ids...)
	return _u
}

// AddRequestQueryParams adds the "request_query_params" edges to the RequestQueryParam entity.
func (_u *RequestUpdateOne) AddRequestQueryParams(v ...*RequestQueryParam) *RequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestQueryParamIDs(ids...)
}

// AddRequestFormFieldIDs adds the "request_form_fields" edge to the RequestFormField entity by IDs.
func (_u *RequestUpdateOne) AddRequestFormFieldIDs(ids ...uuid.UUID) *RequestUpdateOne {
	_u.mutation.AddRequestFormFieldIDs(ids...)
	return _u
}

// AddRequestFormFields adds the "request_form_fields" edges to the RequestFormField entity.
func (_u *RequestUpdateOne) AddRequestFormFields(v ...*RequestFormField) *RequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestFormFieldIDs(ids...)
}

// AddHistoryIDs adds the "histories" edge to the History entity by IDs.
func (_u *RequestUpdateOne) AddHistoryIDs(ids ...uuid.UUID) *RequestUpdateOne {
	_u.mutation.AddHistoryIDs(ids...)
	return _u
}

// AddHistories adds the "histories" edges to the History entity.
func (_u *RequestUpdateOne) AddHistories(v ...*History) *RequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddHistoryIDs(ids...)
}

// Mutation returns the RequestMutation object of the builder.
func (_u *RequestUpdateOne) Mutation() *RequestMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *RequestUpdateOne) ClearWorkspace() *RequestUpdateOne {
	_u.mutation.ClearWorkspace()
	return _u
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (_u *RequestUpdateOne) ClearCollection() *RequestUpdateOne {
	_u.mutation.ClearCollection()
	return _u
}

// ClearRequestHeaders clears all "request_headers" edges to the RequestHeader entity.
func (_u *RequestUpdateOne) ClearRequestHeaders() *RequestUpdateOne {
	_u.mutation.ClearRequestHeaders()
	return _u
}

// RemoveRequestHeaderIDs removes the "request_headers" edge to RequestHeader entities by IDs.
func (_u *RequestUpdateOne) RemoveRequestHeaderIDs(ids ...uuid.UUID) *RequestUpdateOne {
	_u.mutation.RemoveRequestHeaderIDs(ids...)
	return _u
}

// RemoveRequestHeaders removes "request_headers" edges to RequestHeader entities.
func (_u *RequestUpdateOne) RemoveRequestHeaders(v ...*RequestHeader) *RequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestHeaderIDs(ids...)
}

// ClearRequestQueryParams clears all "request_query_params" edges to the RequestQueryParam entity.
func (_u *RequestUpdateOne) ClearRequestQueryParams() *RequestUpdateOne {
	_u.mutation.ClearRequestQueryParams()
	return _u
}

// RemoveRequestQueryParamIDs removes the "request_query_params" edge to RequestQueryParam entities by IDs.
func (_u *RequestUpdateOne) RemoveRequestQueryParamIDs(ids ...uuid.UUID) *RequestUpdateOne {
	_u.mutation.RemoveRequestQueryParamIDs(ids...)
	return _u
}

// RemoveRequestQueryParams removes "request_query_params" edges to RequestQueryParam entities.
func (_u *RequestUpdateOne) RemoveRequestQueryParams(v ...*RequestQueryParam) *RequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestQueryParamIDs(ids...)
}

// ClearRequestFormFields clears all "request_form_fields" edges to the RequestFormField entity.
func (_u *RequestUpdateOne) ClearRequestFormFields() *RequestUpdateOne {
	_u.mutation.ClearRequestFormFields()
	return _u
}

// RemoveRequestFormFieldIDs removes the "request_form_fields" edge to RequestFormField entities by IDs.
func (_u *RequestUpdateOne) RemoveRequestFormFieldIDs(ids ...uuid.UUID) *RequestUpdateOne {
	_u.mutation.RemoveRequestFormFieldIDs(ids...)
	return _u
}

// RemoveRequestFormFields removes "request_form_fields" edges to RequestFormField entities.
func (_u *RequestUpdateOne) RemoveRequestFormFields(v ...*RequestFormField) *RequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestFormFieldIDs(ids...)
}

// ClearHistories clears all "histories" edges to the History entity.
func (_u *RequestUpdateOne) ClearHistories() *RequestUpdateOne {
	_u.mutation.ClearHistories()
	return _u
}

// RemoveHistoryIDs removes the "histories" edge to History entities by IDs.
func (_u *RequestUpdateOne) RemoveHistoryIDs(ids ...uuid.UUID) *RequestUpdateOne {
	_u.mutation.RemoveHistoryIDs(ids...)
	return _u
}

// RemoveHistories removes "histories" edges to History entities.
func (_u *RequestUpdateOne) RemoveHistories(v ...*History) *RequestUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveHistoryIDs(ids...)
}

// Where appends a list predicates to the RequestUpdate builder.
func (_u *RequestUpdateOne) Where(ps ...predicate.Request) *RequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestUpdateOne) Select(field string, fields ...string) *RequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Request entity.
func (_u *RequestUpdateOne) Save(ctx context.Context) (*Request, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestUpdateOne) SaveX(ctx context.Context) *Request {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := request.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := request.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Request.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.URL(); ok {
		if err := request.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Request.url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BodyMode(); ok {
		if err := request.BodyModeValidator(v); err != nil {
			return &ValidationError{Name: "body_mode", err: fmt.Errorf(`ent: validator failed for field "Request.body_mode": %w`, err)}
		}
	}
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Request.workspace"`)
	}
	return nil
}

func (_u *RequestUpdateOne) sqlSave(ctx context.Context) (_node *Request, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(request.Table, request.Columns, sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Request.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, request.FieldID)
		for _, f := range fields {
			if !request.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != request.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(request.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(request.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(request.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodyMode(); ok {
		_spec.SetField(request.FieldBodyMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawBody(); ok {
		_spec.SetField(request.FieldRawBody, field.TypeString, value)
	}
	if _u.mutation.RawBodyCleared() {
		_spec.ClearField(request.FieldRawBody, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(request.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.WorkspaceTable,
			Columns: []string{request.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.WorkspaceTable,
			Columns: []string{request.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.CollectionTable,
			Columns: []string{request.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   request.CollectionTable,
			Columns: []string{request.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestHeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestHeadersTable,
			Columns: []string{request.RequestHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestheader.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestHeadersIDs(); len(nodes) > 0 && !_u.mutation.RequestHeadersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestHeadersTable,
			Columns: []string{request.RequestHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestheader.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestHeadersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestHeadersTable,
			Columns: []string{request.RequestHeadersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestheader.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestQueryParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestQueryParamsTable,
			Columns: []string{request.RequestQueryParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestqueryparam.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestQueryParamsIDs(); len(nodes) > 0 && !_u.mutation.RequestQueryParamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestQueryParamsTable,
			Columns: []string{request.RequestQueryParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestqueryparam.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestQueryParamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestQueryParamsTable,
			Columns: []string{request.RequestQueryParamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestqueryparam.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RequestFormFieldsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestFormFieldsTable,
			Columns: []string{request.RequestFormFieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestformfield.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestFormFieldsIDs(); len(nodes) > 0 && !_u.mutation.RequestFormFieldsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestFormFieldsTable,
			Columns: []string{request.RequestFormFieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestformfield.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestFormFieldsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.RequestFormFieldsTable,
			Columns: []string{request.RequestFormFieldsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(requestformfield.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.HistoriesTable,
			Columns: []string{request.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedHistoriesIDs(); len(nodes) > 0 && !_u.mutation.HistoriesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.HistoriesTable,
			Columns: []string{request.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HistoriesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   request.HistoriesTable,
			Columns: []string{request.HistoriesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(history.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Request{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{request.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
