// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PostmanJanai/ent/request"
	"PostmanJanai/ent/requestqueryparam"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// RequestQueryParam is the model entity for the RequestQueryParam schema.
type RequestQueryParam struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID uuid.UUID `json:"request_id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RequestQueryParamQuery when eager-loading is set.
	Edges        RequestQueryParamEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RequestQueryParamEdges holds the relations/edges for other nodes in the graph.
type RequestQueryParamEdges struct {
	// Request holds the value of the request edge.
	Request *Request `json:"request,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RequestOrErr returns the Request value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RequestQueryParamEdges) RequestOrErr() (*Request, error) {
	if e.Request != nil {
		return e.Request, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: request.Label}
	}
	return nil, &NotLoadedError{edge: "request"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestQueryParam) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestqueryparam.FieldEnabled:
			values[i] = new(sql.NullBool)
		case requestqueryparam.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case requestqueryparam.FieldKey, requestqueryparam.FieldValue:
			values[i] = new(sql.NullString)
		case requestqueryparam.FieldID, requestqueryparam.FieldRequestID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestQueryParam fields.
func (_m *RequestQueryParam) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestqueryparam.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case requestqueryparam.FieldRequestID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value != nil {
				_m.RequestID = *value
			}
		case requestqueryparam.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case requestqueryparam.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		case requestqueryparam.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case requestqueryparam.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the RequestQueryParam.
// This includes values selected through modifiers, order, etc.
func (_m *RequestQueryParam) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryRequest queries the "request" edge of the RequestQueryParam entity.
func (_m *RequestQueryParam) QueryRequest() *RequestQuery {
	return NewRequestQueryParamClient(_m.config).QueryRequest(_m)
}

// Update returns a builder for updating this RequestQueryParam.
// Note that you need to call RequestQueryParam.Unwrap() before calling this method if this RequestQueryParam
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RequestQueryParam) Update() *RequestQueryParamUpdateOne {
	return NewRequestQueryParamClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RequestQueryParam entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RequestQueryParam) Unwrap() *RequestQueryParam {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestQueryParam is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RequestQueryParam) String() string {
	var builder strings.Builder
	builder.WriteString("RequestQueryParam(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("request_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequestID))
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// RequestQueryParams is a parsable slice of RequestQueryParam.
type RequestQueryParams []*RequestQueryParam
