// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PostmanJanai/ent/predicate"
	"PostmanJanai/ent/requestqueryparam"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestQueryParamDelete is the builder for deleting a RequestQueryParam entity.
type RequestQueryParamDelete struct {
	config
	hooks    []Hook
	mutation *RequestQueryParamMutation
}

// Where appends a list predicates to the RequestQueryParamDelete builder.
func (_d *RequestQueryParamDelete) Where(ps ...predicate.RequestQueryParam) *RequestQueryParamDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RequestQueryParamDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestQueryParamDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RequestQueryParamDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(requestqueryparam.Table, sqlgraph.NewFieldSpec(requestqueryparam.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RequestQueryParamDeleteOne is the builder for deleting a single RequestQueryParam entity.
type RequestQueryParamDeleteOne struct {
	_d *RequestQueryParamDelete
}

// Where appends a list predicates to the RequestQueryParamDelete builder.
func (_d *RequestQueryParamDeleteOne) Where(ps ...predicate.RequestQueryParam) *RequestQueryParamDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RequestQueryParamDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{requestqueryparam.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestQueryParamDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
