// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PostmanJanai/ent/request"
	"PostmanJanai/ent/requestassertion"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RequestAssertionCreate is the builder for creating a RequestAssertion entity.
type RequestAssertionCreate struct {
	config
	mutation *RequestAssertionMutation
	hooks    []Hook
}

// SetRequestID sets the "request_id" field.
func (_c *RequestAssertionCreate) SetRequestID(v uuid.UUID) *RequestAssertionCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *RequestAssertionCreate) SetName(v string) *RequestAssertionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *RequestAssertionCreate) SetSource(v string) *RequestAssertionCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetExpression sets the "expression" field.
func (_c *RequestAssertionCreate) SetExpression(v string) *RequestAssertionCreate {
	_c.mutation.SetExpression(v)
	return _c
}

// SetNillableExpression sets the "expression" field if the given value is not nil.
func (_c *RequestAssertionCreate) SetNillableExpression(v *string) *RequestAssertionCreate {
	if v != nil {
		_c.SetExpression(*v)
	}
	return _c
}

// SetOperator sets the "operator" field.
func (_c *RequestAssertionCreate) SetOperator(v string) *RequestAssertionCreate {
	_c.mutation.SetOperator(v)
	return _c
}

// SetExpected sets the "expected" field.
func (_c *RequestAssertionCreate) SetExpected(v string) *RequestAssertionCreate {
	_c.mutation.SetExpected(v)
	return _c
}

// SetNillableExpected sets the "expected" field if the given value is not nil.
func (_c *RequestAssertionCreate) SetNillableExpected(v *string) *RequestAssertionCreate {
	if v != nil {
		_c.SetExpected(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *RequestAssertionCreate) SetEnabled(v bool) *RequestAssertionCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *RequestAssertionCreate) SetNillableEnabled(v *bool) *RequestAssertionCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *RequestAssertionCreate) SetSortOrder(v int) *RequestAssertionCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *RequestAssertionCreate) SetNillableSortOrder(v *int) *RequestAssertionCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RequestAssertionCreate) SetCreatedAt(v time.Time) *RequestAssertionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RequestAssertionCreate) SetNillableCreatedAt(v *time.Time) *RequestAssertionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RequestAssertionCreate) SetUpdatedAt(v time.Time) *RequestAssertionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RequestAssertionCreate) SetNillableUpdatedAt(v *time.Time) *RequestAssertionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RequestAssertionCreate) SetID(v uuid.UUID) *RequestAssertionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RequestAssertionCreate) SetNillableID(v *uuid.UUID) *RequestAssertionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRequest sets the "request" edge to the Request entity.
func (_c *RequestAssertionCreate) SetRequest(v *Request) *RequestAssertionCreate {
	return _c.SetRequestID(v.ID)
}

// Mutation returns the RequestAssertionMutation object of the builder.
func (_c *RequestAssertionCreate) Mutation() *RequestAssertionMutation {
	return _c.mutation
}

// Save creates the RequestAssertion in the database.
func (_c *RequestAssertionCreate) Save(ctx context.Context) (*RequestAssertion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestAssertionCreate) SaveX(ctx context.Context) *RequestAssertion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestAssertionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestAssertionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestAssertionCreate) defaults() {
	if _, ok := _c.mutation.Expression(); !ok {
		v := requestassertion.DefaultExpression
		_c.mutation.SetExpression(v)
	}
	if _, ok := _c.mutation.Expected(); !ok {
		v := requestassertion.DefaultExpected
		_c.mutation.SetExpected(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := requestassertion.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := requestassertion.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := requestassertion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := requestassertion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := requestassertion.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestAssertionCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "RequestAssertion.request_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "RequestAssertion.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := requestassertion.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RequestAssertion.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "RequestAssertion.source"`)}
	}
	if v, ok := _c.mutation.Source(); ok {
		if err := requestassertion.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "RequestAssertion.source": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Expression(); !ok {
		return &ValidationError{Name: "expression", err: errors.New(`ent: missing required field "RequestAssertion.expression"`)}
	}
	if _, ok := _c.mutation.Operator(); !ok {
		return &ValidationError{Name: "operator", err: errors.New(`ent: missing required field "RequestAssertion.operator"`)}
	}
	if v, ok := _c.mutation.Operator(); ok {
		if err := requestassertion.OperatorValidator(v); err != nil {
			return &ValidationError{Name: "operator", err: fmt.Errorf(`ent: validator failed for field "RequestAssertion.operator": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Expected(); !ok {
		return &ValidationError{Name: "expected", err: errors.New(`ent: missing required field "RequestAssertion.expected"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "RequestAssertion.enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "RequestAssertion.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RequestAssertion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RequestAssertion.updated_at"`)}
	}
	if len(_c.mutation.RequestIDs()) == 0 {
		return &ValidationError{Name: "request", err: errors.New(`ent: missing required edge "RequestAssertion.request"`)}
	}
	return nil
}

func (_c *RequestAssertionCreate) sqlSave(ctx context.Context) (*RequestAssertion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestAssertionCreate) createSpec() (*RequestAssertion, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestAssertion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestassertion.Table, sqlgraph.NewFieldSpec(requestassertion.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(requestassertion.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(requestassertion.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Expression(); ok {
		_spec.SetField(requestassertion.FieldExpression, field.TypeString, value)
		_node.Expression = value
	}
	if value, ok := _c.mutation.Operator(); ok {
		_spec.SetField(requestassertion.FieldOperator, field.TypeString, value)
		_node.Operator = value
	}
	if value, ok := _c.mutation.Expected(); ok {
		_spec.SetField(requestassertion.FieldExpected, field.TypeString, value)
		_node.Expected = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(requestassertion.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(requestassertion.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(requestassertion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(requestassertion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestassertion.RequestTable,
			Columns: []string{requestassertion.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RequestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RequestAssertionCreateBulk is the builder for creating many RequestAssertion entities in bulk.
type RequestAssertionCreateBulk struct {
	config
	err      error
	builders []*RequestAssertionCreate
}

// Save creates the RequestAssertion entities in the database.
func (_c *RequestAssertionCreateBulk) Save(ctx context.Context) ([]*RequestAssertion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestAssertion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestAssertionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestAssertionCreateBulk) SaveX(ctx context.Context) []*RequestAssertion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestAssertionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestAssertionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
