// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PostmanJanai/ent/predicate"
	"PostmanJanai/ent/request"
	"PostmanJanai/ent/requestcapture"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RequestCaptureUpdate is the builder for updating RequestCapture entities.
type RequestCaptureUpdate struct {
	config
	hooks    []Hook
	mutation *RequestCaptureMutation
}

// Where appends a list predicates to the RequestCaptureUpdate builder.
func (_u *RequestCaptureUpdate) Where(ps ...predicate.RequestCapture) *RequestCaptureUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RequestCaptureUpdate) SetRequestID(v uuid.UUID) *RequestCaptureUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RequestCaptureUpdate) SetNillableRequestID(v *uuid.UUID) *RequestCaptureUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RequestCaptureUpdate) SetName(v string) *RequestCaptureUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RequestCaptureUpdate) SetNillableName(v *string) *RequestCaptureUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *RequestCaptureUpdate) SetSource(v string) *RequestCaptureUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *RequestCaptureUpdate) SetNillableSource(v *string) *RequestCaptureUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetExpression sets the "expression" field.
func (_u *RequestCaptureUpdate) SetExpression(v string) *RequestCaptureUpdate {
	_u.mutation.SetExpression(v)
	return _u
}

// SetNillableExpression sets the "expression" field if the given value is not nil.
func (_u *RequestCaptureUpdate) SetNillableExpression(v *string) *RequestCaptureUpdate {
	if v != nil {
		_u.SetExpression(*v)
	}
	return _u
}

// SetTargetScope sets the "target_scope" field.
func (_u *RequestCaptureUpdate) SetTargetScope(v string) *RequestCaptureUpdate {
	_u.mutation.SetTargetScope(v)
	return _u
}

// SetNillableTargetScope sets the "target_scope" field if the given value is not nil.
func (_u *RequestCaptureUpdate) SetNillableTargetScope(v *string) *RequestCaptureUpdate {
	if v != nil {
		_u.SetTargetScope(*v)
	}
	return _u
}

// SetTargetVariable sets the "target_variable" field.
func (_u *RequestCaptureUpdate) SetTargetVariable(v string) *RequestCaptureUpdate {
	_u.mutation.SetTargetVariable(v)
	return _u
}

// SetNillableTargetVariable sets the "target_variable" field if the given value is not nil.
func (_u *RequestCaptureUpdate) SetNillableTargetVariable(v *string) *RequestCaptureUpdate {
	if v != nil {
		_u.SetTargetVariable(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RequestCaptureUpdate) SetEnabled(v bool) *RequestCaptureUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RequestCaptureUpdate) SetNillableEnabled(v *bool) *RequestCaptureUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *RequestCaptureUpdate) SetSortOrder(v int) *RequestCaptureUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *RequestCaptureUpdate) SetNillableSortOrder(v *int) *RequestCaptureUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *RequestCaptureUpdate) AddSortOrder(v int) *RequestCaptureUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestCaptureUpdate) SetUpdatedAt(v time.Time) *RequestCaptureUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRequest sets the "request" edge to the Request entity.
func (_u *RequestCaptureUpdate) SetRequest(v *Request) *RequestCaptureUpdate {
	return _u.SetRequestID(v.ID)
}

// Mutation returns the RequestCaptureMutation object of the builder.
func (_u *RequestCaptureUpdate) Mutation() *RequestCaptureMutation {
	return _u.mutation
}

// ClearRequest clears the "request" edge to the Request entity.
func (_u *RequestCaptureUpdate) ClearRequest() *RequestCaptureUpdate {
	_u.mutation.ClearRequest()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RequestCaptureUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestCaptureUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RequestCaptureUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestCaptureUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestCaptureUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := requestcapture.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestCaptureUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := requestcapture.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RequestCapture.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := requestcapture.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "RequestCapture.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetVariable(); ok {
		if err := requestcapture.TargetVariableValidator(v); err != nil {
			return &ValidationError{Name: "target_variable", err: fmt.Errorf(`ent: validator failed for field "RequestCapture.target_variable": %w`, err)}
		}
	}
	if _u.mutation.RequestCleared() && len(_u.mutation.RequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestCapture.request"`)
	}
	return nil
}

func (_u *RequestCaptureUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestcapture.Table, requestcapture.Columns, sqlgraph.NewFieldSpec(requestcapture.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(requestcapture.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(requestcapture.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Expression(); ok {
		_spec.SetField(requestcapture.FieldExpression, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetScope(); ok {
		_spec.SetField(requestcapture.FieldTargetScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetVariable(); ok {
		_spec.SetField(requestcapture.FieldTargetVariable, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(requestcapture.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(requestcapture.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(requestcapture.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestcapture.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestcapture.RequestTable,
			Columns: []string{requestcapture.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestcapture.RequestTable,
			Columns: []string{requestcapture.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestcapture.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RequestCaptureUpdateOne is the builder for updating a single RequestCapture entity.
type RequestCaptureUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RequestCaptureMutation
}

// SetRequestID sets the "request_id" field.
func (_u *RequestCaptureUpdateOne) SetRequestID(v uuid.UUID) *RequestCaptureUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RequestCaptureUpdateOne) SetNillableRequestID(v *uuid.UUID) *RequestCaptureUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RequestCaptureUpdateOne) SetName(v string) *RequestCaptureUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RequestCaptureUpdateOne) SetNillableName(v *string) *RequestCaptureUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *RequestCaptureUpdateOne) SetSource(v string) *RequestCaptureUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *RequestCaptureUpdateOne) SetNillableSource(v *string) *RequestCaptureUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetExpression sets the "expression" field.
func (_u *RequestCaptureUpdateOne) SetExpression(v string) *RequestCaptureUpdateOne {
	_u.mutation.SetExpression(v)
	return _u
}

// SetNillableExpression sets the "expression" field if the given value is not nil.
func (_u *RequestCaptureUpdateOne) SetNillableExpression(v *string) *RequestCaptureUpdateOne {
	if v != nil {
		_u.SetExpression(*v)
	}
	return _u
}

// SetTargetScope sets the "target_scope" field.
func (_u *RequestCaptureUpdateOne) SetTargetScope(v string) *RequestCaptureUpdateOne {
	_u.mutation.SetTargetScope(v)
	return _u
}

// SetNillableTargetScope sets the "target_scope" field if the given value is not nil.
func (_u *RequestCaptureUpdateOne) SetNillableTargetScope(v *string) *RequestCaptureUpdateOne {
	if v != nil {
		_u.SetTargetScope(*v)
	}
	return _u
}

// SetTargetVariable sets the "target_variable" field.
func (_u *RequestCaptureUpdateOne) SetTargetVariable(v string) *RequestCaptureUpdateOne {
	_u.mutation.SetTargetVariable(v)
	return _u
}

// SetNillableTargetVariable sets the "target_variable" field if the given value is not nil.
func (_u *RequestCaptureUpdateOne) SetNillableTargetVariable(v *string) *RequestCaptureUpdateOne {
	if v != nil {
		_u.SetTargetVariable(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *RequestCaptureUpdateOne) SetEnabled(v bool) *RequestCaptureUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *RequestCaptureUpdateOne) SetNillableEnabled(v *bool) *RequestCaptureUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *RequestCaptureUpdateOne) SetSortOrder(v int) *RequestCaptureUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *RequestCaptureUpdateOne) SetNillableSortOrder(v *int) *RequestCaptureUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *RequestCaptureUpdateOne) AddSortOrder(v int) *RequestCaptureUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RequestCaptureUpdateOne) SetUpdatedAt(v time.Time) *RequestCaptureUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRequest sets the "request" edge to the Request entity.
func (_u *RequestCaptureUpdateOne) SetRequest(v *Request) *RequestCaptureUpdateOne {
	return _u.SetRequestID(v.ID)
}

// Mutation returns the RequestCaptureMutation object of the builder.
func (_u *RequestCaptureUpdateOne) Mutation() *RequestCaptureMutation {
	return _u.mutation
}

// ClearRequest clears the "request" edge to the Request entity.
func (_u *RequestCaptureUpdateOne) ClearRequest() *RequestCaptureUpdateOne {
	_u.mutation.ClearRequest()
	return _u
}

// Where appends a list predicates to the RequestCaptureUpdate builder.
func (_u *RequestCaptureUpdateOne) Where(ps ...predicate.RequestCapture) *RequestCaptureUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RequestCaptureUpdateOne) Select(field string, fields ...string) *RequestCaptureUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RequestCapture entity.
func (_u *RequestCaptureUpdateOne) Save(ctx context.Context) (*RequestCapture, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RequestCaptureUpdateOne) SaveX(ctx context.Context) *RequestCapture {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RequestCaptureUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RequestCaptureUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RequestCaptureUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := requestcapture.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RequestCaptureUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := requestcapture.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "RequestCapture.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Source(); ok {
		if err := requestcapture.SourceValidator(v); err != nil {
			return &ValidationError{Name: "source", err: fmt.Errorf(`ent: validator failed for field "RequestCapture.source": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetVariable(); ok {
		if err := requestcapture.TargetVariableValidator(v); err != nil {
			return &ValidationError{Name: "target_variable", err: fmt.Errorf(`ent: validator failed for field "RequestCapture.target_variable": %w`, err)}
		}
	}
	if _u.mutation.RequestCleared() && len(_u.mutation.RequestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RequestCapture.request"`)
	}
	return nil
}

func (_u *RequestCaptureUpdateOne) sqlSave(ctx context.Context) (_node *RequestCapture, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(requestcapture.Table, requestcapture.Columns, sqlgraph.NewFieldSpec(requestcapture.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RequestCapture.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, requestcapture.FieldID)
		for _, f := range fields {
			if !requestcapture.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != requestcapture.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(requestcapture.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(requestcapture.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.Expression(); ok {
		_spec.SetField(requestcapture.FieldExpression, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetScope(); ok {
		_spec.SetField(requestcapture.FieldTargetScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetVariable(); ok {
		_spec.SetField(requestcapture.FieldTargetVariable, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(requestcapture.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(requestcapture.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(requestcapture.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(requestcapture.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RequestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestcapture.RequestTable,
			Columns: []string{requestcapture.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestcapture.RequestTable,
			Columns: []string{requestcapture.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RequestCapture{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{requestcapture.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
