// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PostmanJanai/ent/request"
	"PostmanJanai/ent/requestformfield"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RequestFormFieldCreate is the builder for creating a RequestFormField entity.
type RequestFormFieldCreate struct {
	config
	mutation *RequestFormFieldMutation
	hooks    []Hook
}

// SetRequestID sets the "request_id" field.
func (_c *RequestFormFieldCreate) SetRequestID(v uuid.UUID) *RequestFormFieldCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetFieldKind sets the "field_kind" field.
func (_c *RequestFormFieldCreate) SetFieldKind(v string) *RequestFormFieldCreate {
	_c.mutation.SetFieldKind(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *RequestFormFieldCreate) SetKey(v string) *RequestFormFieldCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *RequestFormFieldCreate) SetValue(v string) *RequestFormFieldCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *RequestFormFieldCreate) SetNillableValue(v *string) *RequestFormFieldCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *RequestFormFieldCreate) SetEnabled(v bool) *RequestFormFieldCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *RequestFormFieldCreate) SetNillableEnabled(v *bool) *RequestFormFieldCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *RequestFormFieldCreate) SetSortOrder(v int) *RequestFormFieldCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *RequestFormFieldCreate) SetNillableSortOrder(v *int) *RequestFormFieldCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RequestFormFieldCreate) SetID(v uuid.UUID) *RequestFormFieldCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RequestFormFieldCreate) SetNillableID(v *uuid.UUID) *RequestFormFieldCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRequest sets the "request" edge to the Request entity.
func (_c *RequestFormFieldCreate) SetRequest(v *Request) *RequestFormFieldCreate {
	return _c.SetRequestID(v.ID)
}

// Mutation returns the RequestFormFieldMutation object of the builder.
func (_c *RequestFormFieldCreate) Mutation() *RequestFormFieldMutation {
	return _c.mutation
}

// Save creates the RequestFormField in the database.
func (_c *RequestFormFieldCreate) Save(ctx context.Context) (*RequestFormField, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RequestFormFieldCreate) SaveX(ctx context.Context) *RequestFormField {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestFormFieldCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestFormFieldCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RequestFormFieldCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := requestformfield.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := requestformfield.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := requestformfield.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RequestFormFieldCreate) check() error {
	if _, ok := _c.mutation.RequestID(); !ok {
		return &ValidationError{Name: "request_id", err: errors.New(`ent: missing required field "RequestFormField.request_id"`)}
	}
	if _, ok := _c.mutation.FieldKind(); !ok {
		return &ValidationError{Name: "field_kind", err: errors.New(`ent: missing required field "RequestFormField.field_kind"`)}
	}
	if v, ok := _c.mutation.FieldKind(); ok {
		if err := requestformfield.FieldKindValidator(v); err != nil {
			return &ValidationError{Name: "field_kind", err: fmt.Errorf(`ent: validator failed for field "RequestFormField.field_kind": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "RequestFormField.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := requestformfield.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "RequestFormField.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "RequestFormField.enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "RequestFormField.sort_order"`)}
	}
	if len(_c.mutation.RequestIDs()) == 0 {
		return &ValidationError{Name: "request", err: errors.New(`ent: missing required edge "RequestFormField.request"`)}
	}
	return nil
}

func (_c *RequestFormFieldCreate) sqlSave(ctx context.Context) (*RequestFormField, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RequestFormFieldCreate) createSpec() (*RequestFormField, *sqlgraph.CreateSpec) {
	var (
		_node = &RequestFormField{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(requestformfield.Table, sqlgraph.NewFieldSpec(requestformfield.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.FieldKind(); ok {
		_spec.SetField(requestformfield.FieldFieldKind, field.TypeString, value)
		_node.FieldKind = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(requestformfield.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(requestformfield.FieldValue, field.TypeString, value)
		_node.Value = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(requestformfield.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(requestformfield.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.RequestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   requestformfield.RequestTable,
			Columns: []string{requestformfield.RequestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(request.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RequestID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RequestFormFieldCreateBulk is the builder for creating many RequestFormField entities in bulk.
type RequestFormFieldCreateBulk struct {
	config
	err      error
	builders []*RequestFormFieldCreate
}

// Save creates the RequestFormField entities in the database.
func (_c *RequestFormFieldCreateBulk) Save(ctx context.Context) ([]*RequestFormField, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RequestFormField, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RequestFormFieldMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RequestFormFieldCreateBulk) SaveX(ctx context.Context) []*RequestFormField {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RequestFormFieldCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RequestFormFieldCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
