// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PostmanJanai/ent/predicate"
	"PostmanJanai/ent/requestformfield"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RequestFormFieldDelete is the builder for deleting a RequestFormField entity.
type RequestFormFieldDelete struct {
	config
	hooks    []Hook
	mutation *RequestFormFieldMutation
}

// Where appends a list predicates to the RequestFormFieldDelete builder.
func (_d *RequestFormFieldDelete) Where(ps ...predicate.RequestFormField) *RequestFormFieldDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RequestFormFieldDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestFormFieldDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RequestFormFieldDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(requestformfield.Table, sqlgraph.NewFieldSpec(requestformfield.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RequestFormFieldDeleteOne is the builder for deleting a single RequestFormField entity.
type RequestFormFieldDeleteOne struct {
	_d *RequestFormFieldDelete
}

// Where appends a list predicates to the RequestFormFieldDelete builder.
func (_d *RequestFormFieldDeleteOne) Where(ps ...predicate.RequestFormField) *RequestFormFieldDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RequestFormFieldDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{requestformfield.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RequestFormFieldDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
