// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PostmanJanai/ent/predicate"
	"PostmanJanai/ent/runnerrun"
	"PostmanJanai/ent/runnerrunrequest"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RunnerRunRequestUpdate is the builder for updating RunnerRunRequest entities.
type RunnerRunRequestUpdate struct {
	config
	hooks    []Hook
	mutation *RunnerRunRequestMutation
}

// Where appends a list predicates to the RunnerRunRequestUpdate builder.
func (_u *RunnerRunRequestUpdate) Where(ps ...predicate.RunnerRunRequest) *RunnerRunRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetRunID sets the "run_id" field.
func (_u *RunnerRunRequestUpdate) SetRunID(v uuid.UUID) *RunnerRunRequestUpdate {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableRunID(v *uuid.UUID) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RunnerRunRequestUpdate) SetRequestID(v uuid.UUID) *RunnerRunRequestUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableRequestID(v *uuid.UUID) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *RunnerRunRequestUpdate) ClearRequestID() *RunnerRunRequestUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetRequestName sets the "request_name" field.
func (_u *RunnerRunRequestUpdate) SetRequestName(v string) *RunnerRunRequestUpdate {
	_u.mutation.SetRequestName(v)
	return _u
}

// SetNillableRequestName sets the "request_name" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableRequestName(v *string) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetRequestName(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *RunnerRunRequestUpdate) SetMethod(v string) *RunnerRunRequestUpdate {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableMethod(v *string) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *RunnerRunRequestUpdate) SetURL(v string) *RunnerRunRequestUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableURL(v *string) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RunnerRunRequestUpdate) SetStatus(v string) *RunnerRunRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableStatus(v *string) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *RunnerRunRequestUpdate) SetStatusCode(v int) *RunnerRunRequestUpdate {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableStatusCode(v *int) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *RunnerRunRequestUpdate) AddStatusCode(v int) *RunnerRunRequestUpdate {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RunnerRunRequestUpdate) SetDurationMs(v int) *RunnerRunRequestUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableDurationMs(v *int) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RunnerRunRequestUpdate) AddDurationMs(v int) *RunnerRunRequestUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetResponseSizeBytes sets the "response_size_bytes" field.
func (_u *RunnerRunRequestUpdate) SetResponseSizeBytes(v int) *RunnerRunRequestUpdate {
	_u.mutation.ResetResponseSizeBytes()
	_u.mutation.SetResponseSizeBytes(v)
	return _u
}

// SetNillableResponseSizeBytes sets the "response_size_bytes" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableResponseSizeBytes(v *int) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetResponseSizeBytes(*v)
	}
	return _u
}

// AddResponseSizeBytes adds value to the "response_size_bytes" field.
func (_u *RunnerRunRequestUpdate) AddResponseSizeBytes(v int) *RunnerRunRequestUpdate {
	_u.mutation.AddResponseSizeBytes(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RunnerRunRequestUpdate) SetErrorMessage(v string) *RunnerRunRequestUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableErrorMessage(v *string) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetAssertionsJSON sets the "assertions_json" field.
func (_u *RunnerRunRequestUpdate) SetAssertionsJSON(v string) *RunnerRunRequestUpdate {
	_u.mutation.SetAssertionsJSON(v)
	return _u
}

// SetNillableAssertionsJSON sets the "assertions_json" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableAssertionsJSON(v *string) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetAssertionsJSON(*v)
	}
	return _u
}

// SetCapturesJSON sets the "captures_json" field.
func (_u *RunnerRunRequestUpdate) SetCapturesJSON(v string) *RunnerRunRequestUpdate {
	_u.mutation.SetCapturesJSON(v)
	return _u
}

// SetNillableCapturesJSON sets the "captures_json" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableCapturesJSON(v *string) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetCapturesJSON(*v)
	}
	return _u
}

// SetRequestHeadersJSON sets the "request_headers_json" field.
func (_u *RunnerRunRequestUpdate) SetRequestHeadersJSON(v string) *RunnerRunRequestUpdate {
	_u.mutation.SetRequestHeadersJSON(v)
	return _u
}

// SetNillableRequestHeadersJSON sets the "request_headers_json" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableRequestHeadersJSON(v *string) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetRequestHeadersJSON(*v)
	}
	return _u
}

// ClearRequestHeadersJSON clears the value of the "request_headers_json" field.
func (_u *RunnerRunRequestUpdate) ClearRequestHeadersJSON() *RunnerRunRequestUpdate {
	_u.mutation.ClearRequestHeadersJSON()
	return _u
}

// SetResponseHeadersJSON sets the "response_headers_json" field.
func (_u *RunnerRunRequestUpdate) SetResponseHeadersJSON(v string) *RunnerRunRequestUpdate {
	_u.mutation.SetResponseHeadersJSON(v)
	return _u
}

// SetNillableResponseHeadersJSON sets the "response_headers_json" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableResponseHeadersJSON(v *string) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetResponseHeadersJSON(*v)
	}
	return _u
}

// ClearResponseHeadersJSON clears the value of the "response_headers_json" field.
func (_u *RunnerRunRequestUpdate) ClearResponseHeadersJSON() *RunnerRunRequestUpdate {
	_u.mutation.ClearResponseHeadersJSON()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *RunnerRunRequestUpdate) SetRequestBody(v string) *RunnerRunRequestUpdate {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableRequestBody(v *string) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *RunnerRunRequestUpdate) ClearRequestBody() *RunnerRunRequestUpdate {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RunnerRunRequestUpdate) SetResponseBody(v string) *RunnerRunRequestUpdate {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableResponseBody(v *string) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *RunnerRunRequestUpdate) ClearResponseBody() *RunnerRunRequestUpdate {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetBodyTruncated sets the "body_truncated" field.
func (_u *RunnerRunRequestUpdate) SetBodyTruncated(v bool) *RunnerRunRequestUpdate {
	_u.mutation.SetBodyTruncated(v)
	return _u
}

// SetNillableBodyTruncated sets the "body_truncated" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableBodyTruncated(v *bool) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetBodyTruncated(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *RunnerRunRequestUpdate) SetSortOrder(v int) *RunnerRunRequestUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *RunnerRunRequestUpdate) SetNillableSortOrder(v *int) *RunnerRunRequestUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *RunnerRunRequestUpdate) AddSortOrder(v int) *RunnerRunRequestUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetRun sets the "run" edge to the RunnerRun entity.
func (_u *RunnerRunRequestUpdate) SetRun(v *RunnerRun) *RunnerRunRequestUpdate {
	return _u.SetRunID(v.ID)
}

// Mutation returns the RunnerRunRequestMutation object of the builder.
func (_u *RunnerRunRequestUpdate) Mutation() *RunnerRunRequestMutation {
	return _u.mutation
}

// ClearRun clears the "run" edge to the RunnerRun entity.
func (_u *RunnerRunRequestUpdate) ClearRun() *RunnerRunRequestUpdate {
	_u.mutation.ClearRun()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RunnerRunRequestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunnerRunRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RunnerRunRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunnerRunRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RunnerRunRequestUpdate) check() error {
	if _u.mutation.RunCleared() && len(_u.mutation.RunIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RunnerRunRequest.run"`)
	}
	return nil
}

func (_u *RunnerRunRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(runnerrunrequest.Table, runnerrunrequest.Columns, sqlgraph.NewFieldSpec(runnerrunrequest.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(runnerrunrequest.FieldRequestID, field.TypeUUID, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(runnerrunrequest.FieldRequestID, field.TypeUUID)
	}
	if value, ok := _u.mutation.RequestName(); ok {
		_spec.SetField(runnerrunrequest.FieldRequestName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(runnerrunrequest.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(runnerrunrequest.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(runnerrunrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(runnerrunrequest.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(runnerrunrequest.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(runnerrunrequest.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(runnerrunrequest.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResponseSizeBytes(); ok {
		_spec.SetField(runnerrunrequest.FieldResponseSizeBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseSizeBytes(); ok {
		_spec.AddField(runnerrunrequest.FieldResponseSizeBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(runnerrunrequest.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssertionsJSON(); ok {
		_spec.SetField(runnerrunrequest.FieldAssertionsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.CapturesJSON(); ok {
		_spec.SetField(runnerrunrequest.FieldCapturesJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHeadersJSON(); ok {
		_spec.SetField(runnerrunrequest.FieldRequestHeadersJSON, field.TypeString, value)
	}
	if _u.mutation.RequestHeadersJSONCleared() {
		_spec.ClearField(runnerrunrequest.FieldRequestHeadersJSON, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseHeadersJSON(); ok {
		_spec.SetField(runnerrunrequest.FieldResponseHeadersJSON, field.TypeString, value)
	}
	if _u.mutation.ResponseHeadersJSONCleared() {
		_spec.ClearField(runnerrunrequest.FieldResponseHeadersJSON, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(runnerrunrequest.FieldRequestBody, field.TypeString, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(runnerrunrequest.FieldRequestBody, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(runnerrunrequest.FieldResponseBody, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(runnerrunrequest.FieldResponseBody, field.TypeString)
	}
	if value, ok := _u.mutation.BodyTruncated(); ok {
		_spec.SetField(runnerrunrequest.FieldBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(runnerrunrequest.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(runnerrunrequest.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.RunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   runnerrunrequest.RunTable,
			Columns: []string{runnerrunrequest.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(runnerrun.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   runnerrunrequest.RunTable,
			Columns: []string{runnerrunrequest.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(runnerrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runnerrunrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RunnerRunRequestUpdateOne is the builder for updating a single RunnerRunRequest entity.
type RunnerRunRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RunnerRunRequestMutation
}

// SetRunID sets the "run_id" field.
func (_u *RunnerRunRequestUpdateOne) SetRunID(v uuid.UUID) *RunnerRunRequestUpdateOne {
	_u.mutation.SetRunID(v)
	return _u
}

// SetNillableRunID sets the "run_id" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableRunID(v *uuid.UUID) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetRunID(*v)
	}
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *RunnerRunRequestUpdateOne) SetRequestID(v uuid.UUID) *RunnerRunRequestUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableRequestID(v *uuid.UUID) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *RunnerRunRequestUpdateOne) ClearRequestID() *RunnerRunRequestUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetRequestName sets the "request_name" field.
func (_u *RunnerRunRequestUpdateOne) SetRequestName(v string) *RunnerRunRequestUpdateOne {
	_u.mutation.SetRequestName(v)
	return _u
}

// SetNillableRequestName sets the "request_name" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableRequestName(v *string) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetRequestName(*v)
	}
	return _u
}

// SetMethod sets the "method" field.
func (_u *RunnerRunRequestUpdateOne) SetMethod(v string) *RunnerRunRequestUpdateOne {
	_u.mutation.SetMethod(v)
	return _u
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableMethod(v *string) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetMethod(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *RunnerRunRequestUpdateOne) SetURL(v string) *RunnerRunRequestUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableURL(v *string) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RunnerRunRequestUpdateOne) SetStatus(v string) *RunnerRunRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableStatus(v *string) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStatusCode sets the "status_code" field.
func (_u *RunnerRunRequestUpdateOne) SetStatusCode(v int) *RunnerRunRequestUpdateOne {
	_u.mutation.ResetStatusCode()
	_u.mutation.SetStatusCode(v)
	return _u
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableStatusCode(v *int) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetStatusCode(*v)
	}
	return _u
}

// AddStatusCode adds value to the "status_code" field.
func (_u *RunnerRunRequestUpdateOne) AddStatusCode(v int) *RunnerRunRequestUpdateOne {
	_u.mutation.AddStatusCode(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RunnerRunRequestUpdateOne) SetDurationMs(v int) *RunnerRunRequestUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableDurationMs(v *int) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RunnerRunRequestUpdateOne) AddDurationMs(v int) *RunnerRunRequestUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetResponseSizeBytes sets the "response_size_bytes" field.
func (_u *RunnerRunRequestUpdateOne) SetResponseSizeBytes(v int) *RunnerRunRequestUpdateOne {
	_u.mutation.ResetResponseSizeBytes()
	_u.mutation.SetResponseSizeBytes(v)
	return _u
}

// SetNillableResponseSizeBytes sets the "response_size_bytes" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableResponseSizeBytes(v *int) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetResponseSizeBytes(*v)
	}
	return _u
}

// AddResponseSizeBytes adds value to the "response_size_bytes" field.
func (_u *RunnerRunRequestUpdateOne) AddResponseSizeBytes(v int) *RunnerRunRequestUpdateOne {
	_u.mutation.AddResponseSizeBytes(v)
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *RunnerRunRequestUpdateOne) SetErrorMessage(v string) *RunnerRunRequestUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableErrorMessage(v *string) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// SetAssertionsJSON sets the "assertions_json" field.
func (_u *RunnerRunRequestUpdateOne) SetAssertionsJSON(v string) *RunnerRunRequestUpdateOne {
	_u.mutation.SetAssertionsJSON(v)
	return _u
}

// SetNillableAssertionsJSON sets the "assertions_json" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableAssertionsJSON(v *string) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetAssertionsJSON(*v)
	}
	return _u
}

// SetCapturesJSON sets the "captures_json" field.
func (_u *RunnerRunRequestUpdateOne) SetCapturesJSON(v string) *RunnerRunRequestUpdateOne {
	_u.mutation.SetCapturesJSON(v)
	return _u
}

// SetNillableCapturesJSON sets the "captures_json" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableCapturesJSON(v *string) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetCapturesJSON(*v)
	}
	return _u
}

// SetRequestHeadersJSON sets the "request_headers_json" field.
func (_u *RunnerRunRequestUpdateOne) SetRequestHeadersJSON(v string) *RunnerRunRequestUpdateOne {
	_u.mutation.SetRequestHeadersJSON(v)
	return _u
}

// SetNillableRequestHeadersJSON sets the "request_headers_json" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableRequestHeadersJSON(v *string) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetRequestHeadersJSON(*v)
	}
	return _u
}

// ClearRequestHeadersJSON clears the value of the "request_headers_json" field.
func (_u *RunnerRunRequestUpdateOne) ClearRequestHeadersJSON() *RunnerRunRequestUpdateOne {
	_u.mutation.ClearRequestHeadersJSON()
	return _u
}

// SetResponseHeadersJSON sets the "response_headers_json" field.
func (_u *RunnerRunRequestUpdateOne) SetResponseHeadersJSON(v string) *RunnerRunRequestUpdateOne {
	_u.mutation.SetResponseHeadersJSON(v)
	return _u
}

// SetNillableResponseHeadersJSON sets the "response_headers_json" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableResponseHeadersJSON(v *string) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetResponseHeadersJSON(*v)
	}
	return _u
}

// ClearResponseHeadersJSON clears the value of the "response_headers_json" field.
func (_u *RunnerRunRequestUpdateOne) ClearResponseHeadersJSON() *RunnerRunRequestUpdateOne {
	_u.mutation.ClearResponseHeadersJSON()
	return _u
}

// SetRequestBody sets the "request_body" field.
func (_u *RunnerRunRequestUpdateOne) SetRequestBody(v string) *RunnerRunRequestUpdateOne {
	_u.mutation.SetRequestBody(v)
	return _u
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableRequestBody(v *string) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetRequestBody(*v)
	}
	return _u
}

// ClearRequestBody clears the value of the "request_body" field.
func (_u *RunnerRunRequestUpdateOne) ClearRequestBody() *RunnerRunRequestUpdateOne {
	_u.mutation.ClearRequestBody()
	return _u
}

// SetResponseBody sets the "response_body" field.
func (_u *RunnerRunRequestUpdateOne) SetResponseBody(v string) *RunnerRunRequestUpdateOne {
	_u.mutation.SetResponseBody(v)
	return _u
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableResponseBody(v *string) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetResponseBody(*v)
	}
	return _u
}

// ClearResponseBody clears the value of the "response_body" field.
func (_u *RunnerRunRequestUpdateOne) ClearResponseBody() *RunnerRunRequestUpdateOne {
	_u.mutation.ClearResponseBody()
	return _u
}

// SetBodyTruncated sets the "body_truncated" field.
func (_u *RunnerRunRequestUpdateOne) SetBodyTruncated(v bool) *RunnerRunRequestUpdateOne {
	_u.mutation.SetBodyTruncated(v)
	return _u
}

// SetNillableBodyTruncated sets the "body_truncated" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableBodyTruncated(v *bool) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetBodyTruncated(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *RunnerRunRequestUpdateOne) SetSortOrder(v int) *RunnerRunRequestUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *RunnerRunRequestUpdateOne) SetNillableSortOrder(v *int) *RunnerRunRequestUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *RunnerRunRequestUpdateOne) AddSortOrder(v int) *RunnerRunRequestUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetRun sets the "run" edge to the RunnerRun entity.
func (_u *RunnerRunRequestUpdateOne) SetRun(v *RunnerRun) *RunnerRunRequestUpdateOne {
	return _u.SetRunID(v.ID)
}

// Mutation returns the RunnerRunRequestMutation object of the builder.
func (_u *RunnerRunRequestUpdateOne) Mutation() *RunnerRunRequestMutation {
	return _u.mutation
}

// ClearRun clears the "run" edge to the RunnerRun entity.
func (_u *RunnerRunRequestUpdateOne) ClearRun() *RunnerRunRequestUpdateOne {
	_u.mutation.ClearRun()
	return _u
}

// Where appends a list predicates to the RunnerRunRequestUpdate builder.
func (_u *RunnerRunRequestUpdateOne) Where(ps ...predicate.RunnerRunRequest) *RunnerRunRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RunnerRunRequestUpdateOne) Select(field string, fields ...string) *RunnerRunRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RunnerRunRequest entity.
func (_u *RunnerRunRequestUpdateOne) Save(ctx context.Context) (*RunnerRunRequest, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunnerRunRequestUpdateOne) SaveX(ctx context.Context) *RunnerRunRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RunnerRunRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunnerRunRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RunnerRunRequestUpdateOne) check() error {
	if _u.mutation.RunCleared() && len(_u.mutation.RunIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RunnerRunRequest.run"`)
	}
	return nil
}

func (_u *RunnerRunRequestUpdateOne) sqlSave(ctx context.Context) (_node *RunnerRunRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(runnerrunrequest.Table, runnerrunrequest.Columns, sqlgraph.NewFieldSpec(runnerrunrequest.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RunnerRunRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, runnerrunrequest.FieldID)
		for _, f := range fields {
			if !runnerrunrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != runnerrunrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(runnerrunrequest.FieldRequestID, field.TypeUUID, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(runnerrunrequest.FieldRequestID, field.TypeUUID)
	}
	if value, ok := _u.mutation.RequestName(); ok {
		_spec.SetField(runnerrunrequest.FieldRequestName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Method(); ok {
		_spec.SetField(runnerrunrequest.FieldMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(runnerrunrequest.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(runnerrunrequest.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StatusCode(); ok {
		_spec.SetField(runnerrunrequest.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStatusCode(); ok {
		_spec.AddField(runnerrunrequest.FieldStatusCode, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(runnerrunrequest.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(runnerrunrequest.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ResponseSizeBytes(); ok {
		_spec.SetField(runnerrunrequest.FieldResponseSizeBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedResponseSizeBytes(); ok {
		_spec.AddField(runnerrunrequest.FieldResponseSizeBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(runnerrunrequest.FieldErrorMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.AssertionsJSON(); ok {
		_spec.SetField(runnerrunrequest.FieldAssertionsJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.CapturesJSON(); ok {
		_spec.SetField(runnerrunrequest.FieldCapturesJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.RequestHeadersJSON(); ok {
		_spec.SetField(runnerrunrequest.FieldRequestHeadersJSON, field.TypeString, value)
	}
	if _u.mutation.RequestHeadersJSONCleared() {
		_spec.ClearField(runnerrunrequest.FieldRequestHeadersJSON, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseHeadersJSON(); ok {
		_spec.SetField(runnerrunrequest.FieldResponseHeadersJSON, field.TypeString, value)
	}
	if _u.mutation.ResponseHeadersJSONCleared() {
		_spec.ClearField(runnerrunrequest.FieldResponseHeadersJSON, field.TypeString)
	}
	if value, ok := _u.mutation.RequestBody(); ok {
		_spec.SetField(runnerrunrequest.FieldRequestBody, field.TypeString, value)
	}
	if _u.mutation.RequestBodyCleared() {
		_spec.ClearField(runnerrunrequest.FieldRequestBody, field.TypeString)
	}
	if value, ok := _u.mutation.ResponseBody(); ok {
		_spec.SetField(runnerrunrequest.FieldResponseBody, field.TypeString, value)
	}
	if _u.mutation.ResponseBodyCleared() {
		_spec.ClearField(runnerrunrequest.FieldResponseBody, field.TypeString)
	}
	if value, ok := _u.mutation.BodyTruncated(); ok {
		_spec.SetField(runnerrunrequest.FieldBodyTruncated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(runnerrunrequest.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(runnerrunrequest.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.RunCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   runnerrunrequest.RunTable,
			Columns: []string{runnerrunrequest.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(runnerrun.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   runnerrunrequest.RunTable,
			Columns: []string{runnerrunrequest.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(runnerrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RunnerRunRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runnerrunrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
