// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PostmanJanai/ent/predicate"
	"PostmanJanai/ent/runnerrun"
	"PostmanJanai/ent/runnerrunrequest"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RunnerRunUpdate is the builder for updating RunnerRun entities.
type RunnerRunUpdate struct {
	config
	hooks    []Hook
	mutation *RunnerRunMutation
}

// Where appends a list predicates to the RunnerRunUpdate builder.
func (_u *RunnerRunUpdate) Where(ps ...predicate.RunnerRun) *RunnerRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetFolderID sets the "folder_id" field.
func (_u *RunnerRunUpdate) SetFolderID(v uuid.UUID) *RunnerRunUpdate {
	_u.mutation.SetFolderID(v)
	return _u
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_u *RunnerRunUpdate) SetNillableFolderID(v *uuid.UUID) *RunnerRunUpdate {
	if v != nil {
		_u.SetFolderID(*v)
	}
	return _u
}

// ClearFolderID clears the value of the "folder_id" field.
func (_u *RunnerRunUpdate) ClearFolderID() *RunnerRunUpdate {
	_u.mutation.ClearFolderID()
	return _u
}

// SetEnvironmentID sets the "environment_id" field.
func (_u *RunnerRunUpdate) SetEnvironmentID(v uuid.UUID) *RunnerRunUpdate {
	_u.mutation.SetEnvironmentID(v)
	return _u
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (_u *RunnerRunUpdate) SetNillableEnvironmentID(v *uuid.UUID) *RunnerRunUpdate {
	if v != nil {
		_u.SetEnvironmentID(*v)
	}
	return _u
}

// ClearEnvironmentID clears the value of the "environment_id" field.
func (_u *RunnerRunUpdate) ClearEnvironmentID() *RunnerRunUpdate {
	_u.mutation.ClearEnvironmentID()
	return _u
}

// SetFolderName sets the "folder_name" field.
func (_u *RunnerRunUpdate) SetFolderName(v string) *RunnerRunUpdate {
	_u.mutation.SetFolderName(v)
	return _u
}

// SetNillableFolderName sets the "folder_name" field if the given value is not nil.
func (_u *RunnerRunUpdate) SetNillableFolderName(v *string) *RunnerRunUpdate {
	if v != nil {
		_u.SetFolderName(*v)
	}
	return _u
}

// SetEnvironmentName sets the "environment_name" field.
func (_u *RunnerRunUpdate) SetEnvironmentName(v string) *RunnerRunUpdate {
	_u.mutation.SetEnvironmentName(v)
	return _u
}

// SetNillableEnvironmentName sets the "environment_name" field if the given value is not nil.
func (_u *RunnerRunUpdate) SetNillableEnvironmentName(v *string) *RunnerRunUpdate {
	if v != nil {
		_u.SetEnvironmentName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RunnerRunUpdate) SetStatus(v string) *RunnerRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RunnerRunUpdate) SetNillableStatus(v *string) *RunnerRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalCount sets the "total_count" field.
func (_u *RunnerRunUpdate) SetTotalCount(v int) *RunnerRunUpdate {
	_u.mutation.ResetTotalCount()
	_u.mutation.SetTotalCount(v)
	return _u
}

// SetNillableTotalCount sets the "total_count" field if the given value is not nil.
func (_u *RunnerRunUpdate) SetNillableTotalCount(v *int) *RunnerRunUpdate {
	if v != nil {
		_u.SetTotalCount(*v)
	}
	return _u
}

// AddTotalCount adds value to the "total_count" field.
func (_u *RunnerRunUpdate) AddTotalCount(v int) *RunnerRunUpdate {
	_u.mutation.AddTotalCount(v)
	return _u
}

// SetPassedCount sets the "passed_count" field.
func (_u *RunnerRunUpdate) SetPassedCount(v int) *RunnerRunUpdate {
	_u.mutation.ResetPassedCount()
	_u.mutation.SetPassedCount(v)
	return _u
}

// SetNillablePassedCount sets the "passed_count" field if the given value is not nil.
func (_u *RunnerRunUpdate) SetNillablePassedCount(v *int) *RunnerRunUpdate {
	if v != nil {
		_u.SetPassedCount(*v)
	}
	return _u
}

// AddPassedCount adds value to the "passed_count" field.
func (_u *RunnerRunUpdate) AddPassedCount(v int) *RunnerRunUpdate {
	_u.mutation.AddPassedCount(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *RunnerRunUpdate) SetFailedCount(v int) *RunnerRunUpdate {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *RunnerRunUpdate) SetNillableFailedCount(v *int) *RunnerRunUpdate {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *RunnerRunUpdate) AddFailedCount(v int) *RunnerRunUpdate {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetErrorCount sets the "error_count" field.
func (_u *RunnerRunUpdate) SetErrorCount(v int) *RunnerRunUpdate {
	_u.mutation.ResetErrorCount()
	_u.mutation.SetErrorCount(v)
	return _u
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_u *RunnerRunUpdate) SetNillableErrorCount(v *int) *RunnerRunUpdate {
	if v != nil {
		_u.SetErrorCount(*v)
	}
	return _u
}

// AddErrorCount adds value to the "error_count" field.
func (_u *RunnerRunUpdate) AddErrorCount(v int) *RunnerRunUpdate {
	_u.mutation.AddErrorCount(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RunnerRunUpdate) SetDurationMs(v int) *RunnerRunUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RunnerRunUpdate) SetNillableDurationMs(v *int) *RunnerRunUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RunnerRunUpdate) AddDurationMs(v int) *RunnerRunUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RunnerRunUpdate) SetNotes(v string) *RunnerRunUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RunnerRunUpdate) SetNillableNotes(v *string) *RunnerRunUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *RunnerRunUpdate) SetFinishedAt(v time.Time) *RunnerRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *RunnerRunUpdate) SetNillableFinishedAt(v *time.Time) *RunnerRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *RunnerRunUpdate) ClearFinishedAt() *RunnerRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// AddRequestIDs adds the "requests" edge to the RunnerRunRequest entity by IDs.
func (_u *RunnerRunUpdate) AddRequestIDs(ids ...uuid.UUID) *RunnerRunUpdate {
	_u.mutation.AddRequestIDs(ids...)
	return _u
}

// AddRequests adds the "requests" edges to the RunnerRunRequest entity.
func (_u *RunnerRunUpdate) AddRequests(v ...*RunnerRunRequest) *RunnerRunUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestIDs(ids...)
}

// Mutation returns the RunnerRunMutation object of the builder.
func (_u *RunnerRunUpdate) Mutation() *RunnerRunMutation {
	return _u.mutation
}

// ClearRequests clears all "requests" edges to the RunnerRunRequest entity.
func (_u *RunnerRunUpdate) ClearRequests() *RunnerRunUpdate {
	_u.mutation.ClearRequests()
	return _u
}

// RemoveRequestIDs removes the "requests" edge to RunnerRunRequest entities by IDs.
func (_u *RunnerRunUpdate) RemoveRequestIDs(ids ...uuid.UUID) *RunnerRunUpdate {
	_u.mutation.RemoveRequestIDs(ids...)
	return _u
}

// RemoveRequests removes "requests" edges to RunnerRunRequest entities.
func (_u *RunnerRunUpdate) RemoveRequests(v ...*RunnerRunRequest) *RunnerRunUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RunnerRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunnerRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RunnerRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunnerRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RunnerRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(runnerrun.Table, runnerrun.Columns, sqlgraph.NewFieldSpec(runnerrun.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FolderID(); ok {
		_spec.SetField(runnerrun.FieldFolderID, field.TypeUUID, value)
	}
	if _u.mutation.FolderIDCleared() {
		_spec.ClearField(runnerrun.FieldFolderID, field.TypeUUID)
	}
	if value, ok := _u.mutation.EnvironmentID(); ok {
		_spec.SetField(runnerrun.FieldEnvironmentID, field.TypeUUID, value)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(runnerrun.FieldEnvironmentID, field.TypeUUID)
	}
	if value, ok := _u.mutation.FolderName(); ok {
		_spec.SetField(runnerrun.FieldFolderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EnvironmentName(); ok {
		_spec.SetField(runnerrun.FieldEnvironmentName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(runnerrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalCount(); ok {
		_spec.SetField(runnerrun.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCount(); ok {
		_spec.AddField(runnerrun.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PassedCount(); ok {
		_spec.SetField(runnerrun.FieldPassedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassedCount(); ok {
		_spec.AddField(runnerrun.FieldPassedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(runnerrun.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(runnerrun.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorCount(); ok {
		_spec.SetField(runnerrun.FieldErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedErrorCount(); ok {
		_spec.AddField(runnerrun.FieldErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(runnerrun.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(runnerrun.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(runnerrun.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(runnerrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(runnerrun.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   runnerrun.RequestsTable,
			Columns: []string{runnerrun.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(runnerrunrequest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestsIDs(); len(nodes) > 0 && !_u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   runnerrun.RequestsTable,
			Columns: []string{runnerrun.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(runnerrunrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   runnerrun.RequestsTable,
			Columns: []string{runnerrun.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(runnerrunrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runnerrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RunnerRunUpdateOne is the builder for updating a single RunnerRun entity.
type RunnerRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RunnerRunMutation
}

// SetFolderID sets the "folder_id" field.
func (_u *RunnerRunUpdateOne) SetFolderID(v uuid.UUID) *RunnerRunUpdateOne {
	_u.mutation.SetFolderID(v)
	return _u
}

// SetNillableFolderID sets the "folder_id" field if the given value is not nil.
func (_u *RunnerRunUpdateOne) SetNillableFolderID(v *uuid.UUID) *RunnerRunUpdateOne {
	if v != nil {
		_u.SetFolderID(*v)
	}
	return _u
}

// ClearFolderID clears the value of the "folder_id" field.
func (_u *RunnerRunUpdateOne) ClearFolderID() *RunnerRunUpdateOne {
	_u.mutation.ClearFolderID()
	return _u
}

// SetEnvironmentID sets the "environment_id" field.
func (_u *RunnerRunUpdateOne) SetEnvironmentID(v uuid.UUID) *RunnerRunUpdateOne {
	_u.mutation.SetEnvironmentID(v)
	return _u
}

// SetNillableEnvironmentID sets the "environment_id" field if the given value is not nil.
func (_u *RunnerRunUpdateOne) SetNillableEnvironmentID(v *uuid.UUID) *RunnerRunUpdateOne {
	if v != nil {
		_u.SetEnvironmentID(*v)
	}
	return _u
}

// ClearEnvironmentID clears the value of the "environment_id" field.
func (_u *RunnerRunUpdateOne) ClearEnvironmentID() *RunnerRunUpdateOne {
	_u.mutation.ClearEnvironmentID()
	return _u
}

// SetFolderName sets the "folder_name" field.
func (_u *RunnerRunUpdateOne) SetFolderName(v string) *RunnerRunUpdateOne {
	_u.mutation.SetFolderName(v)
	return _u
}

// SetNillableFolderName sets the "folder_name" field if the given value is not nil.
func (_u *RunnerRunUpdateOne) SetNillableFolderName(v *string) *RunnerRunUpdateOne {
	if v != nil {
		_u.SetFolderName(*v)
	}
	return _u
}

// SetEnvironmentName sets the "environment_name" field.
func (_u *RunnerRunUpdateOne) SetEnvironmentName(v string) *RunnerRunUpdateOne {
	_u.mutation.SetEnvironmentName(v)
	return _u
}

// SetNillableEnvironmentName sets the "environment_name" field if the given value is not nil.
func (_u *RunnerRunUpdateOne) SetNillableEnvironmentName(v *string) *RunnerRunUpdateOne {
	if v != nil {
		_u.SetEnvironmentName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RunnerRunUpdateOne) SetStatus(v string) *RunnerRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RunnerRunUpdateOne) SetNillableStatus(v *string) *RunnerRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTotalCount sets the "total_count" field.
func (_u *RunnerRunUpdateOne) SetTotalCount(v int) *RunnerRunUpdateOne {
	_u.mutation.ResetTotalCount()
	_u.mutation.SetTotalCount(v)
	return _u
}

// SetNillableTotalCount sets the "total_count" field if the given value is not nil.
func (_u *RunnerRunUpdateOne) SetNillableTotalCount(v *int) *RunnerRunUpdateOne {
	if v != nil {
		_u.SetTotalCount(*v)
	}
	return _u
}

// AddTotalCount adds value to the "total_count" field.
func (_u *RunnerRunUpdateOne) AddTotalCount(v int) *RunnerRunUpdateOne {
	_u.mutation.AddTotalCount(v)
	return _u
}

// SetPassedCount sets the "passed_count" field.
func (_u *RunnerRunUpdateOne) SetPassedCount(v int) *RunnerRunUpdateOne {
	_u.mutation.ResetPassedCount()
	_u.mutation.SetPassedCount(v)
	return _u
}

// SetNillablePassedCount sets the "passed_count" field if the given value is not nil.
func (_u *RunnerRunUpdateOne) SetNillablePassedCount(v *int) *RunnerRunUpdateOne {
	if v != nil {
		_u.SetPassedCount(*v)
	}
	return _u
}

// AddPassedCount adds value to the "passed_count" field.
func (_u *RunnerRunUpdateOne) AddPassedCount(v int) *RunnerRunUpdateOne {
	_u.mutation.AddPassedCount(v)
	return _u
}

// SetFailedCount sets the "failed_count" field.
func (_u *RunnerRunUpdateOne) SetFailedCount(v int) *RunnerRunUpdateOne {
	_u.mutation.ResetFailedCount()
	_u.mutation.SetFailedCount(v)
	return _u
}

// SetNillableFailedCount sets the "failed_count" field if the given value is not nil.
func (_u *RunnerRunUpdateOne) SetNillableFailedCount(v *int) *RunnerRunUpdateOne {
	if v != nil {
		_u.SetFailedCount(*v)
	}
	return _u
}

// AddFailedCount adds value to the "failed_count" field.
func (_u *RunnerRunUpdateOne) AddFailedCount(v int) *RunnerRunUpdateOne {
	_u.mutation.AddFailedCount(v)
	return _u
}

// SetErrorCount sets the "error_count" field.
func (_u *RunnerRunUpdateOne) SetErrorCount(v int) *RunnerRunUpdateOne {
	_u.mutation.ResetErrorCount()
	_u.mutation.SetErrorCount(v)
	return _u
}

// SetNillableErrorCount sets the "error_count" field if the given value is not nil.
func (_u *RunnerRunUpdateOne) SetNillableErrorCount(v *int) *RunnerRunUpdateOne {
	if v != nil {
		_u.SetErrorCount(*v)
	}
	return _u
}

// AddErrorCount adds value to the "error_count" field.
func (_u *RunnerRunUpdateOne) AddErrorCount(v int) *RunnerRunUpdateOne {
	_u.mutation.AddErrorCount(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *RunnerRunUpdateOne) SetDurationMs(v int) *RunnerRunUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *RunnerRunUpdateOne) SetNillableDurationMs(v *int) *RunnerRunUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *RunnerRunUpdateOne) AddDurationMs(v int) *RunnerRunUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *RunnerRunUpdateOne) SetNotes(v string) *RunnerRunUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *RunnerRunUpdateOne) SetNillableNotes(v *string) *RunnerRunUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *RunnerRunUpdateOne) SetFinishedAt(v time.Time) *RunnerRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *RunnerRunUpdateOne) SetNillableFinishedAt(v *time.Time) *RunnerRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *RunnerRunUpdateOne) ClearFinishedAt() *RunnerRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// AddRequestIDs adds the "requests" edge to the RunnerRunRequest entity by IDs.
func (_u *RunnerRunUpdateOne) AddRequestIDs(ids ...uuid.UUID) *RunnerRunUpdateOne {
	_u.mutation.AddRequestIDs(ids...)
	return _u
}

// AddRequests adds the "requests" edges to the RunnerRunRequest entity.
func (_u *RunnerRunUpdateOne) AddRequests(v ...*RunnerRunRequest) *RunnerRunUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRequestIDs(ids...)
}

// Mutation returns the RunnerRunMutation object of the builder.
func (_u *RunnerRunUpdateOne) Mutation() *RunnerRunMutation {
	return _u.mutation
}

// ClearRequests clears all "requests" edges to the RunnerRunRequest entity.
func (_u *RunnerRunUpdateOne) ClearRequests() *RunnerRunUpdateOne {
	_u.mutation.ClearRequests()
	return _u
}

// RemoveRequestIDs removes the "requests" edge to RunnerRunRequest entities by IDs.
func (_u *RunnerRunUpdateOne) RemoveRequestIDs(ids ...uuid.UUID) *RunnerRunUpdateOne {
	_u.mutation.RemoveRequestIDs(ids...)
	return _u
}

// RemoveRequests removes "requests" edges to RunnerRunRequest entities.
func (_u *RunnerRunUpdateOne) RemoveRequests(v ...*RunnerRunRequest) *RunnerRunUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRequestIDs(ids...)
}

// Where appends a list predicates to the RunnerRunUpdate builder.
func (_u *RunnerRunUpdateOne) Where(ps ...predicate.RunnerRun) *RunnerRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RunnerRunUpdateOne) Select(field string, fields ...string) *RunnerRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RunnerRun entity.
func (_u *RunnerRunUpdateOne) Save(ctx context.Context) (*RunnerRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RunnerRunUpdateOne) SaveX(ctx context.Context) *RunnerRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RunnerRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RunnerRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *RunnerRunUpdateOne) sqlSave(ctx context.Context) (_node *RunnerRun, err error) {
	_spec := sqlgraph.NewUpdateSpec(runnerrun.Table, runnerrun.Columns, sqlgraph.NewFieldSpec(runnerrun.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RunnerRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, runnerrun.FieldID)
		for _, f := range fields {
			if !runnerrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != runnerrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FolderID(); ok {
		_spec.SetField(runnerrun.FieldFolderID, field.TypeUUID, value)
	}
	if _u.mutation.FolderIDCleared() {
		_spec.ClearField(runnerrun.FieldFolderID, field.TypeUUID)
	}
	if value, ok := _u.mutation.EnvironmentID(); ok {
		_spec.SetField(runnerrun.FieldEnvironmentID, field.TypeUUID, value)
	}
	if _u.mutation.EnvironmentIDCleared() {
		_spec.ClearField(runnerrun.FieldEnvironmentID, field.TypeUUID)
	}
	if value, ok := _u.mutation.FolderName(); ok {
		_spec.SetField(runnerrun.FieldFolderName, field.TypeString, value)
	}
	if value, ok := _u.mutation.EnvironmentName(); ok {
		_spec.SetField(runnerrun.FieldEnvironmentName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(runnerrun.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TotalCount(); ok {
		_spec.SetField(runnerrun.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTotalCount(); ok {
		_spec.AddField(runnerrun.FieldTotalCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.PassedCount(); ok {
		_spec.SetField(runnerrun.FieldPassedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPassedCount(); ok {
		_spec.AddField(runnerrun.FieldPassedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.FailedCount(); ok {
		_spec.SetField(runnerrun.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailedCount(); ok {
		_spec.AddField(runnerrun.FieldFailedCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ErrorCount(); ok {
		_spec.SetField(runnerrun.FieldErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedErrorCount(); ok {
		_spec.AddField(runnerrun.FieldErrorCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(runnerrun.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(runnerrun.FieldDurationMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(runnerrun.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(runnerrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(runnerrun.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   runnerrun.RequestsTable,
			Columns: []string{runnerrun.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(runnerrunrequest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRequestsIDs(); len(nodes) > 0 && !_u.mutation.RequestsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   runnerrun.RequestsTable,
			Columns: []string{runnerrun.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(runnerrunrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   runnerrun.RequestsTable,
			Columns: []string{runnerrun.RequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(runnerrunrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RunnerRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{runnerrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
