// Code generated by ent, DO NOT EDIT.

package ent

import (
	"PostmanJanai/ent/runnerrun"
	"PostmanJanai/ent/runnerrunrequest"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RunnerRunRequestCreate is the builder for creating a RunnerRunRequest entity.
type RunnerRunRequestCreate struct {
	config
	mutation *RunnerRunRequestMutation
	hooks    []Hook
}

// SetRunID sets the "run_id" field.
func (_c *RunnerRunRequestCreate) SetRunID(v uuid.UUID) *RunnerRunRequestCreate {
	_c.mutation.SetRunID(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *RunnerRunRequestCreate) SetRequestID(v uuid.UUID) *RunnerRunRequestCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableRequestID(v *uuid.UUID) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetRequestName sets the "request_name" field.
func (_c *RunnerRunRequestCreate) SetRequestName(v string) *RunnerRunRequestCreate {
	_c.mutation.SetRequestName(v)
	return _c
}

// SetNillableRequestName sets the "request_name" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableRequestName(v *string) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetRequestName(*v)
	}
	return _c
}

// SetMethod sets the "method" field.
func (_c *RunnerRunRequestCreate) SetMethod(v string) *RunnerRunRequestCreate {
	_c.mutation.SetMethod(v)
	return _c
}

// SetNillableMethod sets the "method" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableMethod(v *string) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetMethod(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *RunnerRunRequestCreate) SetURL(v string) *RunnerRunRequestCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableURL(v *string) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetURL(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RunnerRunRequestCreate) SetStatus(v string) *RunnerRunRequestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableStatus(v *string) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetStatusCode sets the "status_code" field.
func (_c *RunnerRunRequestCreate) SetStatusCode(v int) *RunnerRunRequestCreate {
	_c.mutation.SetStatusCode(v)
	return _c
}

// SetNillableStatusCode sets the "status_code" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableStatusCode(v *int) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetStatusCode(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *RunnerRunRequestCreate) SetDurationMs(v int) *RunnerRunRequestCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableDurationMs(v *int) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetResponseSizeBytes sets the "response_size_bytes" field.
func (_c *RunnerRunRequestCreate) SetResponseSizeBytes(v int) *RunnerRunRequestCreate {
	_c.mutation.SetResponseSizeBytes(v)
	return _c
}

// SetNillableResponseSizeBytes sets the "response_size_bytes" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableResponseSizeBytes(v *int) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetResponseSizeBytes(*v)
	}
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *RunnerRunRequestCreate) SetErrorMessage(v string) *RunnerRunRequestCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableErrorMessage(v *string) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetAssertionsJSON sets the "assertions_json" field.
func (_c *RunnerRunRequestCreate) SetAssertionsJSON(v string) *RunnerRunRequestCreate {
	_c.mutation.SetAssertionsJSON(v)
	return _c
}

// SetNillableAssertionsJSON sets the "assertions_json" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableAssertionsJSON(v *string) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetAssertionsJSON(*v)
	}
	return _c
}

// SetCapturesJSON sets the "captures_json" field.
func (_c *RunnerRunRequestCreate) SetCapturesJSON(v string) *RunnerRunRequestCreate {
	_c.mutation.SetCapturesJSON(v)
	return _c
}

// SetNillableCapturesJSON sets the "captures_json" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableCapturesJSON(v *string) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetCapturesJSON(*v)
	}
	return _c
}

// SetRequestHeadersJSON sets the "request_headers_json" field.
func (_c *RunnerRunRequestCreate) SetRequestHeadersJSON(v string) *RunnerRunRequestCreate {
	_c.mutation.SetRequestHeadersJSON(v)
	return _c
}

// SetNillableRequestHeadersJSON sets the "request_headers_json" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableRequestHeadersJSON(v *string) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetRequestHeadersJSON(*v)
	}
	return _c
}

// SetResponseHeadersJSON sets the "response_headers_json" field.
func (_c *RunnerRunRequestCreate) SetResponseHeadersJSON(v string) *RunnerRunRequestCreate {
	_c.mutation.SetResponseHeadersJSON(v)
	return _c
}

// SetNillableResponseHeadersJSON sets the "response_headers_json" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableResponseHeadersJSON(v *string) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetResponseHeadersJSON(*v)
	}
	return _c
}

// SetRequestBody sets the "request_body" field.
func (_c *RunnerRunRequestCreate) SetRequestBody(v string) *RunnerRunRequestCreate {
	_c.mutation.SetRequestBody(v)
	return _c
}

// SetNillableRequestBody sets the "request_body" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableRequestBody(v *string) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetRequestBody(*v)
	}
	return _c
}

// SetResponseBody sets the "response_body" field.
func (_c *RunnerRunRequestCreate) SetResponseBody(v string) *RunnerRunRequestCreate {
	_c.mutation.SetResponseBody(v)
	return _c
}

// SetNillableResponseBody sets the "response_body" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableResponseBody(v *string) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetResponseBody(*v)
	}
	return _c
}

// SetBodyTruncated sets the "body_truncated" field.
func (_c *RunnerRunRequestCreate) SetBodyTruncated(v bool) *RunnerRunRequestCreate {
	_c.mutation.SetBodyTruncated(v)
	return _c
}

// SetNillableBodyTruncated sets the "body_truncated" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableBodyTruncated(v *bool) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetBodyTruncated(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *RunnerRunRequestCreate) SetSortOrder(v int) *RunnerRunRequestCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableSortOrder(v *int) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RunnerRunRequestCreate) SetCreatedAt(v time.Time) *RunnerRunRequestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableCreatedAt(v *time.Time) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RunnerRunRequestCreate) SetID(v uuid.UUID) *RunnerRunRequestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RunnerRunRequestCreate) SetNillableID(v *uuid.UUID) *RunnerRunRequestCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRun sets the "run" edge to the RunnerRun entity.
func (_c *RunnerRunRequestCreate) SetRun(v *RunnerRun) *RunnerRunRequestCreate {
	return _c.SetRunID(v.ID)
}

// Mutation returns the RunnerRunRequestMutation object of the builder.
func (_c *RunnerRunRequestCreate) Mutation() *RunnerRunRequestMutation {
	return _c.mutation
}

// Save creates the RunnerRunRequest in the database.
func (_c *RunnerRunRequestCreate) Save(ctx context.Context) (*RunnerRunRequest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RunnerRunRequestCreate) SaveX(ctx context.Context) *RunnerRunRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunnerRunRequestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunnerRunRequestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RunnerRunRequestCreate) defaults() {
	if _, ok := _c.mutation.RequestName(); !ok {
		v := runnerrunrequest.DefaultRequestName
		_c.mutation.SetRequestName(v)
	}
	if _, ok := _c.mutation.Method(); !ok {
		v := runnerrunrequest.DefaultMethod
		_c.mutation.SetMethod(v)
	}
	if _, ok := _c.mutation.URL(); !ok {
		v := runnerrunrequest.DefaultURL
		_c.mutation.SetURL(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := runnerrunrequest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		v := runnerrunrequest.DefaultStatusCode
		_c.mutation.SetStatusCode(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := runnerrunrequest.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.ResponseSizeBytes(); !ok {
		v := runnerrunrequest.DefaultResponseSizeBytes
		_c.mutation.SetResponseSizeBytes(v)
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		v := runnerrunrequest.DefaultErrorMessage
		_c.mutation.SetErrorMessage(v)
	}
	if _, ok := _c.mutation.AssertionsJSON(); !ok {
		v := runnerrunrequest.DefaultAssertionsJSON
		_c.mutation.SetAssertionsJSON(v)
	}
	if _, ok := _c.mutation.CapturesJSON(); !ok {
		v := runnerrunrequest.DefaultCapturesJSON
		_c.mutation.SetCapturesJSON(v)
	}
	if _, ok := _c.mutation.BodyTruncated(); !ok {
		v := runnerrunrequest.DefaultBodyTruncated
		_c.mutation.SetBodyTruncated(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := runnerrunrequest.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := runnerrunrequest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := runnerrunrequest.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RunnerRunRequestCreate) check() error {
	if _, ok := _c.mutation.RunID(); !ok {
		return &ValidationError{Name: "run_id", err: errors.New(`ent: missing required field "RunnerRunRequest.run_id"`)}
	}
	if _, ok := _c.mutation.RequestName(); !ok {
		return &ValidationError{Name: "request_name", err: errors.New(`ent: missing required field "RunnerRunRequest.request_name"`)}
	}
	if _, ok := _c.mutation.Method(); !ok {
		return &ValidationError{Name: "method", err: errors.New(`ent: missing required field "RunnerRunRequest.method"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "RunnerRunRequest.url"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RunnerRunRequest.status"`)}
	}
	if _, ok := _c.mutation.StatusCode(); !ok {
		return &ValidationError{Name: "status_code", err: errors.New(`ent: missing required field "RunnerRunRequest.status_code"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "RunnerRunRequest.duration_ms"`)}
	}
	if _, ok := _c.mutation.ResponseSizeBytes(); !ok {
		return &ValidationError{Name: "response_size_bytes", err: errors.New(`ent: missing required field "RunnerRunRequest.response_size_bytes"`)}
	}
	if _, ok := _c.mutation.ErrorMessage(); !ok {
		return &ValidationError{Name: "error_message", err: errors.New(`ent: missing required field "RunnerRunRequest.error_message"`)}
	}
	if _, ok := _c.mutation.AssertionsJSON(); !ok {
		return &ValidationError{Name: "assertions_json", err: errors.New(`ent: missing required field "RunnerRunRequest.assertions_json"`)}
	}
	if _, ok := _c.mutation.CapturesJSON(); !ok {
		return &ValidationError{Name: "captures_json", err: errors.New(`ent: missing required field "RunnerRunRequest.captures_json"`)}
	}
	if _, ok := _c.mutation.BodyTruncated(); !ok {
		return &ValidationError{Name: "body_truncated", err: errors.New(`ent: missing required field "RunnerRunRequest.body_truncated"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "RunnerRunRequest.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RunnerRunRequest.created_at"`)}
	}
	if len(_c.mutation.RunIDs()) == 0 {
		return &ValidationError{Name: "run", err: errors.New(`ent: missing required edge "RunnerRunRequest.run"`)}
	}
	return nil
}

func (_c *RunnerRunRequestCreate) sqlSave(ctx context.Context) (*RunnerRunRequest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RunnerRunRequestCreate) createSpec() (*RunnerRunRequest, *sqlgraph.CreateSpec) {
	var (
		_node = &RunnerRunRequest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(runnerrunrequest.Table, sqlgraph.NewFieldSpec(runnerrunrequest.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(runnerrunrequest.FieldRequestID, field.TypeUUID, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.RequestName(); ok {
		_spec.SetField(runnerrunrequest.FieldRequestName, field.TypeString, value)
		_node.RequestName = value
	}
	if value, ok := _c.mutation.Method(); ok {
		_spec.SetField(runnerrunrequest.FieldMethod, field.TypeString, value)
		_node.Method = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(runnerrunrequest.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(runnerrunrequest.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StatusCode(); ok {
		_spec.SetField(runnerrunrequest.FieldStatusCode, field.TypeInt, value)
		_node.StatusCode = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(runnerrunrequest.FieldDurationMs, field.TypeInt, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.ResponseSizeBytes(); ok {
		_spec.SetField(runnerrunrequest.FieldResponseSizeBytes, field.TypeInt, value)
		_node.ResponseSizeBytes = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(runnerrunrequest.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = value
	}
	if value, ok := _c.mutation.AssertionsJSON(); ok {
		_spec.SetField(runnerrunrequest.FieldAssertionsJSON, field.TypeString, value)
		_node.AssertionsJSON = value
	}
	if value, ok := _c.mutation.CapturesJSON(); ok {
		_spec.SetField(runnerrunrequest.FieldCapturesJSON, field.TypeString, value)
		_node.CapturesJSON = value
	}
	if value, ok := _c.mutation.RequestHeadersJSON(); ok {
		_spec.SetField(runnerrunrequest.FieldRequestHeadersJSON, field.TypeString, value)
		_node.RequestHeadersJSON = &value
	}
	if value, ok := _c.mutation.ResponseHeadersJSON(); ok {
		_spec.SetField(runnerrunrequest.FieldResponseHeadersJSON, field.TypeString, value)
		_node.ResponseHeadersJSON = &value
	}
	if value, ok := _c.mutation.RequestBody(); ok {
		_spec.SetField(runnerrunrequest.FieldRequestBody, field.TypeString, value)
		_node.RequestBody = &value
	}
	if value, ok := _c.mutation.ResponseBody(); ok {
		_spec.SetField(runnerrunrequest.FieldResponseBody, field.TypeString, value)
		_node.ResponseBody = &value
	}
	if value, ok := _c.mutation.BodyTruncated(); ok {
		_spec.SetField(runnerrunrequest.FieldBodyTruncated, field.TypeBool, value)
		_node.BodyTruncated = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(runnerrunrequest.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(runnerrunrequest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RunIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   runnerrunrequest.RunTable,
			Columns: []string{runnerrunrequest.RunColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(runnerrun.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RunID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// RunnerRunRequestCreateBulk is the builder for creating many RunnerRunRequest entities in bulk.
type RunnerRunRequestCreateBulk struct {
	config
	err      error
	builders []*RunnerRunRequestCreate
}

// Save creates the RunnerRunRequest entities in the database.
func (_c *RunnerRunRequestCreateBulk) Save(ctx context.Context) ([]*RunnerRunRequest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RunnerRunRequest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RunnerRunRequestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RunnerRunRequestCreateBulk) SaveX(ctx context.Context) []*RunnerRunRequest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RunnerRunRequestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RunnerRunRequestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
