// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {context} from '../models';

export function ClearActive():Promise<void>;

export function Create(arg1:string,arg2:string):Promise<entity.EnvironmentFull>;

export function Delete(arg1:string):Promise<void>;

export function Get(arg1:string):Promise<entity.EnvironmentFull>;

export function GetActive():Promise<entity.EnvironmentSummary>;

export function List():Promise<Array<entity.EnvironmentSummary>>;

export function SaveVariables(arg1:string,arg2:Array<entity.EnvVariableInput>):Promise<void>;

export function SetActive(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateMeta(arg1:string,arg2:string,arg3:string):Promise<void>;
