// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPostmanV21(arg1) {
  return window['go']['delivery']['ExportHandler']['ExportPostmanV21'](arg1);
}

export function SetContext(arg1) {
  return window['go']['delivery']['ExportHandler']['SetContext'](arg1);
}
