// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {context} from '../models';

export function CreateFolder(arg1:entity.CreateFolderInput):Promise<entity.FolderItem>;

export function DeleteFolder(arg1:string):Promise<void>;

export function ListChildFolders(arg1:string):Promise<Array<entity.FolderItem>>;

export function ListRootFolders():Promise<Array<entity.FolderItem>>;

export function SetContext(arg1:context.Context):Promise<void>;

export function UpdateFolder(arg1:string,arg2:string,arg3:string):Promise<void>;
