// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Delete(arg1) {
  return window['go']['delivery']['HistoryHandler']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['delivery']['HistoryHandler']['Get'](arg1);
}

export function List(arg1) {
  return window['go']['delivery']['HistoryHandler']['List'](arg1);
}

export function SetContext(arg1) {
  return window['go']['delivery']['HistoryHandler']['SetContext'](arg1);
}
