// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Execute(arg1) {
  return window['go']['delivery']['HTTPHandler']['Execute'](arg1);
}

export function ImportFromCurl(arg1) {
  return window['go']['delivery']['HTTPHandler']['ImportFromCurl'](arg1);
}

export function PickFileForBody() {
  return window['go']['delivery']['HTTPHandler']['PickFileForBody']();
}

export function SetContext(arg1) {
  return window['go']['delivery']['HTTPHandler']['SetContext'](arg1);
}
