// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {context} from '../models';

export function ListAssertions(arg1:string):Promise<Array<entity.RequestAssertionRow>>;

export function ListCaptures(arg1:string):Promise<Array<entity.RequestCaptureRow>>;

export function SaveAssertions(arg1:string,arg2:Array<entity.RequestAssertionInput>):Promise<Array<entity.RequestAssertionRow>>;

export function SaveCaptures(arg1:string,arg2:Array<entity.RequestCaptureInput>):Promise<Array<entity.RequestCaptureRow>>;

export function SetContext(arg1:context.Context):Promise<void>;
