// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['delivery']['SavedRequestHandler']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['delivery']['SavedRequestHandler']['Delete'](arg1);
}

export function Duplicate(arg1) {
  return window['go']['delivery']['SavedRequestHandler']['Duplicate'](arg1);
}

export function Get(arg1) {
  return window['go']['delivery']['SavedRequestHandler']['Get'](arg1);
}

export function ListByFolder(arg1) {
  return window['go']['delivery']['SavedRequestHandler']['ListByFolder'](arg1);
}

export function MoveRequest(arg1, arg2) {
  return window['go']['delivery']['SavedRequestHandler']['MoveRequest'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['delivery']['SavedRequestHandler']['SetContext'](arg1);
}

export function Update(arg1) {
  return window['go']['delivery']['SavedRequestHandler']['Update'](arg1);
}
