// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entity} from '../models';
import {context} from '../models';

export function AddTrustedCA(arg1:string,arg2:string):Promise<void>;

export function DeleteTrustedCA(arg1:string):Promise<void>;

export function GetProxySettings():Promise<entity.ProxySettings>;

export function ListTrustedCAs():Promise<Array<entity.TrustedCASummary>>;

export function PickCACertFile():Promise<string>;

export function ReadTextFile(arg1:string):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetProxySettings(arg1:entity.ProxySettings):Promise<void>;

export function SetTrustedCAEnabled(arg1:string,arg2:boolean):Promise<void>;

export function TestProxy(arg1:string):Promise<entity.ProxyTestResult>;
