// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListSnippetKinds() {
  return window['go']['delivery']['SnippetHandler']['ListSnippetKinds']();
}

export function RenderSnippet(arg1, arg2) {
  return window['go']['delivery']['SnippetHandler']['RenderSnippet'](arg1, arg2);
}

export function SetContext(arg1) {
  return window['go']['delivery']['SnippetHandler']['SetContext'](arg1);
}
