// Code generated by ent, DO NOT EDIT.

package workspace

import (
	"PostmanJanai/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldID, id))
}

// WorkspaceName applies equality check predicate on the "workspace_name" field. It's identical to WorkspaceNameEQ.
func WorkspaceName(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldWorkspaceName, v))
}

// WorkspaceDescription applies equality check predicate on the "workspace_description" field. It's identical to WorkspaceDescriptionEQ.
func WorkspaceDescription(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldWorkspaceDescription, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCreatedAt, v))
}

// WorkspaceNameEQ applies the EQ predicate on the "workspace_name" field.
func WorkspaceNameEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldWorkspaceName, v))
}

// WorkspaceNameNEQ applies the NEQ predicate on the "workspace_name" field.
func WorkspaceNameNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldWorkspaceName, v))
}

// WorkspaceNameIn applies the In predicate on the "workspace_name" field.
func WorkspaceNameIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldWorkspaceName, vs...))
}

// WorkspaceNameNotIn applies the NotIn predicate on the "workspace_name" field.
func WorkspaceNameNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldWorkspaceName, vs...))
}

// WorkspaceNameGT applies the GT predicate on the "workspace_name" field.
func WorkspaceNameGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldWorkspaceName, v))
}

// WorkspaceNameGTE applies the GTE predicate on the "workspace_name" field.
func WorkspaceNameGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldWorkspaceName, v))
}

// WorkspaceNameLT applies the LT predicate on the "workspace_name" field.
func WorkspaceNameLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldWorkspaceName, v))
}

// WorkspaceNameLTE applies the LTE predicate on the "workspace_name" field.
func WorkspaceNameLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldWorkspaceName, v))
}

// WorkspaceNameContains applies the Contains predicate on the "workspace_name" field.
func WorkspaceNameContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldWorkspaceName, v))
}

// WorkspaceNameHasPrefix applies the HasPrefix predicate on the "workspace_name" field.
func WorkspaceNameHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldWorkspaceName, v))
}

// WorkspaceNameHasSuffix applies the HasSuffix predicate on the "workspace_name" field.
func WorkspaceNameHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldWorkspaceName, v))
}

// WorkspaceNameEqualFold applies the EqualFold predicate on the "workspace_name" field.
func WorkspaceNameEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldWorkspaceName, v))
}

// WorkspaceNameContainsFold applies the ContainsFold predicate on the "workspace_name" field.
func WorkspaceNameContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldWorkspaceName, v))
}

// WorkspaceDescriptionEQ applies the EQ predicate on the "workspace_description" field.
func WorkspaceDescriptionEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldWorkspaceDescription, v))
}

// WorkspaceDescriptionNEQ applies the NEQ predicate on the "workspace_description" field.
func WorkspaceDescriptionNEQ(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldWorkspaceDescription, v))
}

// WorkspaceDescriptionIn applies the In predicate on the "workspace_description" field.
func WorkspaceDescriptionIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldWorkspaceDescription, vs...))
}

// WorkspaceDescriptionNotIn applies the NotIn predicate on the "workspace_description" field.
func WorkspaceDescriptionNotIn(vs ...string) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldWorkspaceDescription, vs...))
}

// WorkspaceDescriptionGT applies the GT predicate on the "workspace_description" field.
func WorkspaceDescriptionGT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldWorkspaceDescription, v))
}

// WorkspaceDescriptionGTE applies the GTE predicate on the "workspace_description" field.
func WorkspaceDescriptionGTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldWorkspaceDescription, v))
}

// WorkspaceDescriptionLT applies the LT predicate on the "workspace_description" field.
func WorkspaceDescriptionLT(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldWorkspaceDescription, v))
}

// WorkspaceDescriptionLTE applies the LTE predicate on the "workspace_description" field.
func WorkspaceDescriptionLTE(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldWorkspaceDescription, v))
}

// WorkspaceDescriptionContains applies the Contains predicate on the "workspace_description" field.
func WorkspaceDescriptionContains(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContains(FieldWorkspaceDescription, v))
}

// WorkspaceDescriptionHasPrefix applies the HasPrefix predicate on the "workspace_description" field.
func WorkspaceDescriptionHasPrefix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasPrefix(FieldWorkspaceDescription, v))
}

// WorkspaceDescriptionHasSuffix applies the HasSuffix predicate on the "workspace_description" field.
func WorkspaceDescriptionHasSuffix(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldHasSuffix(FieldWorkspaceDescription, v))
}

// WorkspaceDescriptionEqualFold applies the EqualFold predicate on the "workspace_description" field.
func WorkspaceDescriptionEqualFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldEqualFold(FieldWorkspaceDescription, v))
}

// WorkspaceDescriptionContainsFold applies the ContainsFold predicate on the "workspace_description" field.
func WorkspaceDescriptionContainsFold(v string) predicate.Workspace {
	return predicate.Workspace(sql.FieldContainsFold(FieldWorkspaceDescription, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Workspace {
	return predicate.Workspace(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Workspace) predicate.Workspace {
	return predicate.Workspace(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Workspace) predicate.Workspace {
	return predicate.Workspace(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Workspace) predicate.Workspace {
	return predicate.Workspace(sql.NotPredicates(p))
}
